define({
    // Connection tab
    "connection": "Verbindung",
    // Clients container
    "clients": "Clients",
    "newClients": "Neue Clients",
    // "addTrustedClient": "",
    "trustedClients": "Vertraute Clients",
    "removeTrustedClient": "Entfernen",
    // "troubleshooting": "",
    // Manually add client page
    "manAddClient": "Manuelles hinzufügen eines Clients",
    "addClient": "Client hinzufügen",
    // "deviceName": "",
    // "deviceNameHelp": "",
    // "clientHostname": "",
    // "clientHostnameHelp": "",
    "ipAddress": "IP-Address",
    "ipHelp": "Bekannte IP-Addresse des HMD eingeben",
    "addClientButton": "Client hinzufügen",
    // Configure client page
    // "configureClient": "",
    // "configureClientButton": "",
    // "configureClientAddIp": "",
    // "configureClientRemoveIp": "",
    // Statistics container
    "statistics": "Statistiken",
    "streamingStatistics": "Streaming Statistiken",
    "totalPackets": "Alle Packets",
    "packetRate": "PacketRate",
    "packetsLostTotal": "Gesamter Packets-Verlust",
    "packetsLostPerSecond": "Packets verloren pro sekunde",
    "totalSent": "Alle gesendeten",
    "sentRate": "Gesendete Rate",
    "totalLatency": "Gesamte Verzögerung",
    "encodeLatency": "Verschlüsselungs Verzögerung",
    "encodeLatencyMax": "Verschlüsselungs Verzögerung max",
    "transportLatency": "Transport Verzögerung",
    "decodeLatency": "Entschlüsselungs latency",
    "fecPercentage": "Fec Prozentsatz",
    "fecFailureTotal": "Fec Verlust gesamt",
    "fecFailureInSecond": "Fec Verlust pro sekunde",
    "clientFPS": "Client fps",
    "serverFPS": "Server fps",
    "packets": "Packets",
    "packetss": "Packets/s",
    // Logging tab
    "logging": "Protokollierung",
    // validation errors
    // "error_DuplicateHostname": "",
    // "error_DuplicateIp": "",
    // "error_InvalidIp": "",
    // Performance graphs tab
    // "performanceGraphs": "",
    // "performanceEncode": "",
    // "performanceDecode": "",
    // "performanceTransport": "",
    // "performanceOther": "",
    // "performanceLatency": "",
    // "performanceFramerate": "",
    // "performanceNoDateCaptured": "",
});