define({
    "connection": "客户端连接",
    "logging": "日志记录",
    "clients": "客户端",
    "newClients": "可连接的新客户端",
    "trustedClients": "已信任的客户端",
    "manAddClient": "手动添加客户端",
    "statistics": "串流状态信息",
    "addClient": "Add client",
    "clientType": "Type",
    "ipAddress": "IP地址",
    "ipHelp": "Enter know IP-address of the HMD",
    "addClientButton": "Add client",
    "totalPackets": "数据包总数",
    "packetRate": "封包速率",
    "packetsLostTotal": "丢包数",
    "packetsLostPerSecond": "每秒丢失数据包数",
    "totalSent": "已发送流量",
    "sentRate": "网络速度",
    "totalLatency": "总延迟",
    "encodeLatency": "编码延迟",
    "encodeLatencyMax": "最高编码延迟",
    "transportLatency": "传输延迟",
    "decodeLatency": "解码延迟",
    "fecPercentage": "Fec 百分比",
    "fecFailureTotal": "Fec 总丢失数据包数",
    "fecFailureInSecond": "Fec 每秒丢失数据包数",
    "clientFPS": "客户端帧数",
    "serverFPS": "服务端帧数",
    "packets": "个数据包",
    "packetss": "个数据包每秒"
});