define({
    "title": "欢迎使用ALVR - k7Ysh5A_4.1.汉化",
    "subtitle": "此向导将指导您进行ALVR的基本设置",
    "titleHardwareReq": "硬件需求",
    "textHardwareReq": "ALVR要求独立显卡支持，这里可以查看 <a target='_blank' href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>所有支持的显卡</a>。 <br/> <br/> 确保你至少有一个音频输出设备。",
    "titleSoftwareReq": "软件要求",
    "textSoftwareReq": "确保你已经正确安装SteamVR, 至少运行一次以后并关闭。<br/> <br/> 如果你没有准备好，请首先安装 <a  target='_blank' href='https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads'>Visual C++ 64位运行库</a> 安装包。 <br/> <br/> 串流Quest的麦克风至电脑需要安装 <a  target='_blank' href='https://www.vb-audio.com/Cable/'>Virtual Audio Cable</a>.",
    "titleFirewall": "防火墙",
    "textFirewall": "要和头戴显示器进行通讯，需要设置一些防火墙规则。这将要求以管理员模式运行。",
    "buttonFirewall": "添加防火墙规则",
    "titleDriver": "驱动程序",
    "textDriver": "ALVR驱动程序需要在SteamVR中注册",
    "buttonDriver": "注册驱动程序",
    "titleTracking": "追踪速度",
    "textTracking": "应该如何处理控制器的跟踪。如果您打算玩节奏快的游戏（如Beatsaber），请选择中速或快速。对于较慢的游戏（如《天际》），请使其保持正常。",
    "normalTracking": "正常",
    "mediumTracking": "中速",
    "fastTracking": "快速",
    "titlePerformance": "性能预设",
    "textPerformance": "请选择适合您的设置的预设。这将为您调整一些设置。",
    "compatPerformance": "性能",
    "qualityPerformance": "画质",
    "titleFinished": "完成",
    "textFinished": "您始终可以从左侧的”安装“标签重新启动此向导",
    "buttonNext": "下一步",
    "buttonClose": "关闭",
    "driverFailed": "注册驱动程序失败",
    "driverSuccess": "驱动程序成功注册",
    "firewallFailed": "设置防火墙规则失败",
    "firewallSuccess": "防火墙规则已成功设置"
});