define({
    // Connection tab
    "connection": "Conexión",
    // Clients container
    "clients": "Clientes",
    "newClients": "Nuevos clientes",
    // "addTrustedClient": "",
    "trustedClients": "Clientes de confianza",
    "removeTrustedClient": "Quitar",
    // "troubleshooting": "",
    // Manually add client page
    "manAddClient": "Añadir un cliente manualmente",
    "addClient": "Añadir cliente",
    // "deviceName": "",
    // "deviceNameHelp": "",
    // "clientHostname": "",
    // "clientHostnameHelp": "",
    "ipAddress": "Dirección IP",
    "ipHelp": "Añade la dirección IP remota del vidor",
    "addClientButton": "Añadir cliente",
    // Configure client page
    // "configureClient": "",
    // "configureClientButton": "",
    // "configureClientAddIp": "",
    // "configureClientRemoveIp": "",
    // Statistics container
    "statistics": "Estadísticas",
    "streamingStatistics": "Estadísticas de transmisión",
    "totalPackets": "Paquetes totales",
    "packetRate": "Velocidad de envío de paquetes (total)",
    "packetsLostTotal": "Total de paquetes perdidos",
    "packetsLostPerSecond": "Paquetes perdidos por segundo",
    "totalSent": "Total de paquetes enviados",
    "sentRate": "Velocidad de envío de paquetes",
    "totalLatency": "Latencia total",
    "encodeLatency": "Latencia del codificador de vídeo",
    "encodeLatencyMax": "Máxima latencia del codificador de vídeo",
    "transportLatency": "Latencia de transmisión",
    "decodeLatency": "Latencia del decodificador de video",
    "fecPercentage": "Porcentaje de corrección de errores (FEC)",
    "fecFailureTotal": "Errores totales FEC",
    "fecFailureInSecond": "Errores FEC por segundo",
    "clientFPS": "FPS del cliente",
    "serverFPS": "FPS del servidor",
    "packets": "Paquetes",
    "packetss": "Paquetes/s",
    // Logging tab
    "logging": "Registros",
    // validation errors
    // "error_DuplicateHostname": "",
    // "error_DuplicateIp": "",
    // "error_InvalidIp": "",
    // Performance graphs tab
    // "performanceGraphs": "",
    // "performanceEncode": "",
    // "performanceDecode": "",
    // "performanceTransport": "",
    // "performanceOther": "",
    // "performanceLatency": "",
    // "performanceFramerate": "",
    // "performanceNoDateCaptured": "",
});