define({
    "connection": "Conexión",
    "logging": "Registros",
    "clients": "Clientes",
    "newClients": "Nuevos clientes",
    "trustedClients": "Clientes de confianza",
    "manAddClient": "Añadir un cliente manualmente",
    "statistics": "Estadísticas de transmisión",
    "addClient": "Añadir cliente",
    "clientType": "Tipo",
    "ipAddress": "Dirección IP",
    "ipHelp": "Añade la dirección IP remota del vidor",
    "addClientButton": "Añadir cliente",
    "totalPackets": "Paquetes totales",
    "packetRate": "Velocidad de envío de paquetes (total)",
    "packetsLostTotal": "Total de paquetes perdidos",
    "packetsLostPerSecond": "Paquetes perdidos por segundo",
    "totalSent": "Total de paquetes enviados",
    "sentRate": "Velocidad de envío de paquetes",
    "totalLatency": "Latencia total",
    "encodeLatency": "Latencia del codificador de vídeo",
    "encodeLatencyMax": "Máxima latencia del codificador de vídeo",
    "transportLatency": "Latencia de transmisión",
    "decodeLatency": "Latencia del decodificador de video",
    "fecPercentage": "Porcentaje de corrección de errores (FEC)",
    "fecFailureTotal": "Errores totales FEC",
    "fecFailureInSecond": "Errores FEC por segundo",
    "clientFPS": "FPS del cliente",
    "serverFPS": "FPS del servidor",
    "packets" : "Paquetes",
    "packetss" : "Paquetes/s"
});