define({
    "title": "Bienvenido a ALVR",
    "subtitle": "Esta guía le ayudará a instalar y configurar ALVR",
    "titleHardwareReq": "Requisitos de hardware",
    "textHardwareReq": "ALVR requiere una tarjeta gráfica dedicada reciente (los gráficos Intel HD no son compatibles). Aquí puedes ver una <a target='_blank' href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>lista de GPUs soportadas</a>. <br/> <br/> Asegúrate de tener al menos un dispositivo de salida de audio.",
    "titleSoftwareReq": "Requisitos de software",
    "textSoftwareReq": "Para transmitir el audio desde el micrófono del visor necesitas instalar <a  target='_blank' href='https://www.vb-audio.com/Cable/'>VB-Audio Virtual Cable</a>.",
    "titleFirewall": "Cortafuegos",
    "textFirewall": "Para comunicarse con el visor se deben establecer ciertas excepciones en el cortafuegos. Esto requiere privilegios de administrador.",
    "buttonFirewall": "Añadir excepción al cortafuegos",
    "titleDriver": "Controlador",
    "textDriver": "El controlador de ALVR debe estar registrado en SteamVR. Si ya está presente, retire los controladores de previas versiones que puedan interferir. (Si no sabes qué hacer, quita todos los controladores y luego registra el controlador de ALVR.)",
    "buttonDriver": "Registrar controlador de ALVR",
    "titleTracking": "Seguimiento",
    "textTracking": `Elija el modo de seguimiento para los mandos. Los juegos frenéticos como BeatSaber requieren un modo "rápido". Para juegos más tranquilos como Skyrim, elige "medio" o "lento".`,
    "normalTracking": "Lento",
    "mediumTracking": "Medio",
    "fastTracking": "Rápido",
    "titlePerformance": "Ajustes de rendimiento",
    "textPerformance": "Elija el modo que mejor se adapte a su PC. Algunos valores se ajustarán automáticamente.",
    "compatPerformance": "Compatibilidad",
    "qualityPerformance": "Calidad visual",
    "titleFinished": "Listo!",
    "textFinished": `Puedes reiniciar esta guía desde la sección "Instalación" en el menu la izquierda.`,
    "buttonNext": "Siguiente",
    "buttonClose": "Cerrar",
    "driverFailed": "El registro del controlador ha fallado",
    "driverSuccess": "Se ha registrado el controlador con éxito",
    "firewallFailed": "Error al añadir la excepción al cortafuegos",
    "firewallSuccess": "Se ha añadido la excepción al cortafuegos con éxito",
    "YourGPUIs": "Tu GPU es",
    "GPUSupported": "Excelente! Esta placa de video esta probablemente soportada!",
    "GPUUnsupported": "Lo sentimos, pero esta placa de video no parece soportada. Puedes probar ALVR y ver si funciona.",
    "GPUUnknown": "Oops. Parece que tu GPU está desconectada o que tienes una papa en su lugar.",
    "titleTheme": "Estilo",
    "textTheme": "Elija su lado; claro u oscuro",
    "darklyTheme": "Oscuro",
    "classicTheme": "Clasico"
});