define({
    "connection": "Подключение",
    "logging": "Журнал",
    "clients": "Клиенты",
    "newClients": "Новые клиенты",
    "trustedClients": "Одобренные клиенты",
    "manAddClient": "Добавить клиента вручную",
    "removeTrustedClient": "удалить",
    "statistics": "Статистика Трансляции",
    "addClient": "Добавить клиента",
    "ipAddress": "IP-Адрес",
    "ipHelp": "Введите известный адрес гарнитуры",
    "addClientButton": "Добавить клиента",
    "totalPackets": "Всего пакетов",
    "packetRate": "Скорость передачи пакетов",
    "packetsLostTotal": "Всего пакетов потеряно",
    "packetsLostPerSecond": "Пакетов потеряно/с",
    "totalSent": "Всего отправлено",
    "sentRate": "Отправка в секунду",
    "totalLatency": "Общая задержка",
    "encodeLatency": "Задержка энкодера",
    "encodeLatencyMax": "Максимальная задержка энкодера",
    "transportLatency": "Задержка передачи",
    "decodeLatency": "Задержка декодера",
    "fecPercentage": "Общий процент упреждающей коррекции ошибок (FEC)",
    "fecFailureTotal": "Всего ошибок FEC",
    "fecFailureInSecond": "Ошибок FEC/с",
    "clientFPS": "FPS клиента",
    "serverFPS": "FPS сервера",
    "packets": "пакетов",
    "packetss": "пакетов/с"
});