define({
    "customVideoScale": "настраиваемое разрешение",
    "steamVRRestartSuccess": "SteamVR успешно перезапущен",
    "_root_video_tab.name": "Видео",
    "_root_audio_tab.name": "Аудио",
    "_root_headset_tab.name": "Гарнитура",
    "_root_connection_tab.name": "Подключение",
    "_root_extra_tab.name": "Дополнительно",

    "_root_video_adapterIndex.name": "Индекс GPU",
    "_root_video_encodeBitrateMbs.name": "Битрейт видео",
    "_root_video_encodeBitrateMbs.description": "Битрейт трансляции видео. 30Мб/с - рекомендуемый. \nБолее высокий битрейт обеспечивает более качественное изображение, но при этом повышается задержка и кол-во сетевого трафика.",
    "_root_video_resolutionDropdown.name": "Разрешение видео",
    "_root_video_resolutionDropdown.description": `100% обеспечивает нативное разрешение Oculus Quest 2880x1600.
    Изменение разрешения не рекомендовано, однако оно может улучшить визуальные впечатления. 
    Разрешение меньше 100% может уменьшить задержку и увеличить производительность сети.`,
    "_root_video_renderResolution-choice-.name": "Изменение разрешения видео",
    "_root_video_recommendedTargetResolution-choice-.name": "Предпочитаемое разрешение рендеринга игр",
   "_root_video_ipd.name": "Межзрачковое расстояние",
    "_root_video_foveatedRendering.name": "Реновированный рендеринг",
    "_root_video_foveatedRendering_enabled.description": `Реновированный рендеринг (Foveated rendering) - техника рендеринга, при которой центр изображения обрабатывается в высоком разрешении, а периферийные участки - в значительно пониженном.
    Обеспечивает более низкое разрешение видео, передаваемого по сети.
    Видео меньшего объема при том же битрейте сохраняет больше деталей и, в то же время, уменьшает задержку.`,
    "_root_video_foveatedRendering_content_strength.name": "Сила",
    "_root_video_foveatedRendering_content_strength.description": "Более высокое значение уменьшает кол-во деталей у краев поля видимости и увеличивает кол-во артефактов.",
    "_root_video_foveatedRendering_content_shape.description": "Форма реновированного рендеринга.",
    "_root_video_foveatedRendering_content_verticalOffset.name": "Вертикальный сдвиг",
    "_root_video_foveatedRendering_content_verticalOffset.description": "Более высокое значение обеспечивает смещение более качественной области кадра вниз.",
    "_root_video_colorCorrection.name": "Коррекция цвета",
    "_root_video_colorCorrection_content_brightness.name": "Яркость",
    "_root_video_colorCorrection_content_contrast.name": "Контраст",
    "_root_video_colorCorrection_content_saturation.name": "Насыщенность",
    "_root_video_colorCorrection_content_gamma.name": "Гамма",
    "_root_video_colorCorrection_content_gamma.description": "Также регулирует яркость, но сохраняет черный цвет черным, а белый - белым.",
    "_root_video_colorCorrection_content_sharpening.name": "Четкость",
    "_root_video_codec-choice-.name": "Кодек видео",
    "_root_video_codec-choice-.description": "HEVC предпочитаем для получения более качественного изображения на низком битрейте. Лучше всего с HEVC с видеокартами AMD.",
    "_root_video_codec_H264-choice-.name": "h264",
    "_root_video_codec_HEVC-choice-.name": "HEVC (h265)",
    
    "_root_audio_gameAudio.name": "Передача звука игры",
    "_root_audio_gameAudio_content_deviceDropdown.name": "Выберите устройство воспроизведения",
    "_root_audio_gameAudio_content_deviceDropdown.description": "Устройство воспроизведения используется для захвата звука.",
    "_root_audio_microphone.name": "Трансляция микрофона",
    "_root_audio_microphone.description": "Передает сигнал микрофона гарнитуры.",
    "_root_audio_microphone_content_deviceDropdown.name": "Выберите виртуальное устройство ввода",
    "_root_audio_microphone_content_deviceDropdown.description": "Чтобы ваш микрофон заработал, необходимо установить VB-CABLE Virtual Audio Device или другое аналогичное ПО.",
    
    "_root_headset_trackingFrameOffset.name": "Задержка отслеживания",
    "_root_headset_trackingFrameOffset.description": "Задержка алгоритма предсказания расположения гарнитуры.",
    "_root_headset_positionOffset.name": "Смещение положения гарнитуры",
    "_root_headset_positionOffset_0.name": "x",
    "_root_headset_positionOffset_1.name": "y",
    "_root_headset_positionOffset_2.name": "z",
    "_root_headset_force3dof.name": "Принудительное отслеживание 3Dof",
    "_root_headset_force3dof.description": "Принудительное отслеживание 3-х степеней свободы (как в Oculus Go).",
    "_root_headset_controllers.name": "Контроллеры",
    "_root_headset_controllers_content_poseTimeOffset.name": "Задержка отслеживания положения",
    "_root_headset_controllers_content_poseTimeOffset.description": "Задержка алгоритма предсказания расположения контроллеров.",
    "_root_headset_controllers_content_positionOffsetLeft.name": "Смещение положения",
    "_root_headset_controllers_content_positionOffsetLeft.description": "Смещение положения в метрах для левого контроллера. \nДля правого контроллера, значение для оси x отражено.",
    "_root_headset_controllers_content_positionOffsetLeft_0.name": "x",
    "_root_headset_controllers_content_positionOffsetLeft_1.name": "y",
    "_root_headset_controllers_content_positionOffsetLeft_2.name": "z",
    "_root_headset_controllers_content_rotationOffsetLeft.name": "Смещение поворота",
    "_root_headset_controllers_content_rotationOffsetLeft.description": "Смещение поворота в градусах для левого контроллера.\nДля правого контроллера, повороты по осям Y и Z отражены.",
    "_root_headset_controllers_content_rotationOffsetLeft_0.name": "x",
    "_root_headset_controllers_content_rotationOffsetLeft_1.name": "y",
    "_root_headset_controllers_content_rotationOffsetLeft_2.name": "z",
    "_root_headset_controllers_content_hapticsIntensity.name": "Интенсивность тактильной отдачи",
    "_root_headset_headsetEmulationMode.name": "Режим эмуляции гарнитуры",
    "_root_headset_headsetEmulationMode.description": "Эмулирует разные гарнитуры для лучшей совместимости.",
    "_root_headset_controllers_content_controllerMode.name": "Режим эмуляции контроллеров",
    "_root_headset_controllers_content_controllerMode.description": "Эмулирует разные контроллеры для лучшей совместимости или использования отслеживания рук.",
    "_root_connection_listenPort.name": "Порт сервера трансляции",
    "_root_connection_throttlingBitrateBits.name": "Макс. битрейт трансляции",
    "_root_connection_clientRecvBufferSize.name": "Размер буфера клиента",
    "_root_connection_clientRecvBufferSize.description": "Размер буфера на клиентской стороне, зависит от битрейта.\n Рекомендуется рассчитанный размер . Если вы испытываете потерю пакетов - увеличьте буфер.",
    "_root_connection_frameQueueSize.description": "Максимум кадров в очереди.",
    "_root_connection_aggressiveKeyframeResend.name": "Интенсивный повтор отправки пакетов",
    "_root_connection_aggressiveKeyframeResend.description": `Уменьшает минимальный интервал между ключевыми кадрами со 100мс до 5мс.
    Используется только когда наблюдается потеря пакетов. Улучшает работу в сетях с большой потерей пакетов.`,
    "_root_connection_disableThrottling.name": "Отключить пропуск тактов",
    "_root_connection_disableThrottling.description": "Отключение пропуска (дросселирования) тактов. Отсылает данные настолько быстро, насколько это возможно.",
    "_root_connection_suppressFrameDrop.name": "Подавить потерю кадров",
    "_root_connection_bufferOffset.name": "Смещение буфера",
    "_root_connection_bufferOffset.description": "Смещение для увеличения или уменьшения рассчитанного размера буфера. Размер буфера клиента не может быть отрицательным.",
    
    "_root_extra_revertConfirmDialog.name": "Подтверждать восстановление",
    "_root_extra_revertConfirmDialog.description": "Запрашивать подтверждение перед откатом параметра к стандартному значению.",
    "_root_extra_restartConfirmDialog.name": "Подтверждать перезапуск",
    "_root_extra_restartConfirmDialog.description": "Запрашивать подтверждение перед перезапуском SteamVR.",
    "audioDeviceError": "Не найдены устройства воспроизведения. Невозможно транслировать звук или микрофон",
    "_root_extra_theme-choice-.name": "Оформление",
    "_root_extra_theme-choice-.description": "Переходи на темную сторону!\n ...у нас тут есть печеньки.",
    "_root_extra_theme_systemDefault-choice-.name": "Системная",
    "_root_extra_theme_classic-choice-.name": "Классическая",
    "_root_extra_theme_darkly-choice-.name": "Темная",
});