accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MPL-2.0",
    "OpenSSL",
    "Unlicense",
    "Zlib",
    "zlib-acknowledgement",
    "GPL-3.0", # only for optional code
]

targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "aarch64-linux-android",
    "wasm32-unknown-unknown",
]
