define({
    // Connection tab
    connection: "Подключение",
    // Clients container
    clients: "Клиенты",
    newClients: "Новые клиенты",
    // "addTrustedClient": "",
    trustedClients: "Одобренные клиенты",
    removeTrustedClient: "удалить",
    // "troubleshooting": "",
    // Manually add client page
    manAddClient: "Добавить клиента вручную",
    addClient: "Добавить клиента",
    // "deviceName": "",
    // "deviceNameHelp": "",
    // "clientHostname": "",
    // "clientHostnameHelp": "",
    ipAddress: "IP-Адрес",
    ipHelp: "Введите известный адрес гарнитуры",
    addClientButton: "Добавить клиента",
    // Configure client page
    // "configureClient": "",
    // "configureClientButton": "",
    // "configureClientAddIp": "",
    // "configureClientRemoveIp": "",
    // Statistics container
    statistics: "Статистика",
    streamingStatistics: "Статистика Трансляции",
    totalPackets: "Всего пакетов",
    packetRate: "Скорость передачи пакетов",
    packetsLostTotal: "Всего пакетов потеряно",
    packetsLostPerSecond: "Пакетов потеряно/с",
    totalSent: "Всего отправлено",
    sentRate: "Отправка в секунду",
    totalLatency: "Общая задержка",
    encodeLatency: "Задержка энкодера",
    encodeLatencyMax: "Максимальная задержка энкодера",
    transportLatency: "Задержка передачи",
    decodeLatency: "Задержка декодера",
    fecPercentage: "Общий процент упреждающей коррекции ошибок (FEC)",
    fecFailureTotal: "Всего ошибок FEC",
    fecFailureInSecond: "Ошибок FEC/с",
    clientFPS: "FPS клиента",
    serverFPS: "FPS сервера",
    packets: "пакетов",
    packetss: "пакетов/с",
    // Logging tab
    logging: "Журнал",
    // validation errors
    // "error_DuplicateHostname": "",
    // "error_DuplicateIp": "",
    // "error_InvalidIp": "",
    // Performance graphs tab
    // "performanceGraphs": "",
    // "performanceEncode": "",
    // "performanceDecode": "",
    // "performanceTransport": "",
    // "performanceOther": "",
    // "performanceLatency": "",
    // "performanceFramerate": "",
    // "performanceNoDateCaptured": "",
});
