#include "FreePIE.h"
#include "packet_types.h"

// Map FreePIE button id to RemoteController button id
const int FreePIE::BUTTON_MAP[FreePIE::ALVR_FREEPIE_BUTTONS] = {
	ALVR_INPUT_SYSTEM_CLICK, ALVR_INPUT_APPLICATION_MENU_CLICK, ALVR_INPUT_GRIP_CLICK
	, ALVR_INPUT_DPAD_LEFT_CLICK, ALVR_INPUT_DPAD_UP_CLICK, ALVR_INPUT_DPAD_RIGHT_CLICK, ALVR_INPUT_DPAD_DOWN_CLICK
	, ALVR_INPUT_A_CLICK, ALVR_INPUT_B_CLICK, ALVR_INPUT_X_CLICK, ALVR_INPUT_Y_CLICK
	, ALVR_INPUT_TRACKPAD_CLICK, ALVR_INPUT_TRACKPAD_TOUCH, ALVR_INPUT_TRIGGER_CLICK
	, ALVR_INPUT_SHOULDER_LEFT_CLICK, ALVR_INPUT_SHOULDER_RIGHT_CLICK
	, ALVR_INPUT_JOYSTICK_LEFT_CLICK, ALVR_INPUT_JOYSTICK_RIGHT_CLICK
	, ALVR_INPUT_BACK_CLICK, ALVR_INPUT_GUIDE_CLICK, ALVR_INPUT_START_CLICK
};