define({
    "connection": "Connessione",
    "logging": "Log",
    "clients": "Client",
    "newClients": "Nuovi client",
    "trustedClients": "Client attendibili",
    "manAddClient": "Aggiungi client manualmente",
    "statistics": "Statistiche di streaming",
    "addClient": "Aggiungi client",
    "clientType": "Tipo",
    "ipAddress": "Indirizzo IP",
    "ipHelp": "Aggiungi l'indirizzo IP remoto del visore",
    "addClientButton": "Aggiungi client",
    "totalPackets": "Totale pacchetti",
    "packetRate": "Velocità di invio pacchetti (totale)",
    "packetsLostTotal": "Totale pacchetti persi",
    "packetsLostPerSecond": "Pacchetti persi al secondo",
    "totalSent": "Totale pacchetti inviati",
    "sentRate": "Velocità di invio pacchetti",
    "totalLatency": "Latenza totale",
    "encodeLatency": "Latenza dell'encoder video",
    "encodeLatencyMax": "Latenza massima dell'encoder video",
    "transportLatency": "Latenza di trasmissione",
    "decodeLatency": "Latenza del decoder video",
    "fecPercentage": "percentuale per correzione errori (FEC)",
    "fecFailureTotal": "Totale errori FEC",
    "fecFailureInSecond": "Errori FEC al secondo",
    "clientFPS": "FPS del client",
    "serverFPS": "FPS del server",
    "packets" : "Pacchetti",
    "packetss" : "Pacchetti/s"
});