define({
    "connection": "Verbindung",
    "logging": "Protokollierung",
    "clients": "Clients",
    "newClients": "Neue Clients",
    "trustedClients": "Vertraute Clients",
    "manAddClient": "Manuelles hinzufügen eines Clients",
    "removeTrustedClient": "Entfernen",
    "statistics": "Streaming Statistiken",
    "addClient": "Client hinzufügen",
    "ipAddress": "IP-Address",
    "ipHelp": "Bekannte IP-Addresse des HMD eingeben",
    "addClientButton": "Client hinzufügen",
    "totalPackets": "Alle Packets",
    "packetRate": "PacketRate",
    "packetsLostTotal": "Gesamter Packets-Verlust",
    "packetsLostPerSecond": "Packets verloren pro sekunde",
    "totalSent": "Alle gesendeten",
    "sentRate": "Gesendete Rate",
    "totalLatency": "Gesamte Verzögerung",
    "encodeLatency": "Verschlüsselungs Verzögerung",
    "encodeLatencyMax": "Verschlüsselungs Verzögerung max",
    "transportLatency": "Transport Verzögerung",
    "decodeLatency": "Entschlüsselungs latency",
    "fecPercentage": "Fec Prozentsatz",
    "fecFailureTotal": "Fec Verlust gesamt",
    "fecFailureInSecond": "Fec Verlust pro sekunde",
    "clientFPS": "Client fps",
    "serverFPS": "Server fps",
    "packets": "Packets",
    "packetss": "Packets/s"
});