define({
    "title": "Wilkommen zu ALVR",
    "subtitle": "Hier wirst du durchs Standard-Setup von ALVR geleitet",
    "titleHardwareReq": "Benötigte Hardware",
    "textHardwareReq": "ALVR benötigt eine dedicated und aktuelle Grafikkarte (Intel HD Graphics ist nicht unterstützt). Hier ist die <a href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>Liste von Unterstützen GPUs</a>. <br/> <br/> Stelle sicher, dass du mindestens ein Audio-Output-Gerät hast.",
    "titleSoftwareReq": "Benötigte Software",
    "textSoftwareReq": "Um das Quest Mikrofon zu streamen musst du das <a  href='https://www.vb-audio.com/Cable/'>VB-Audio Virtual Cable installieren</a>.",
    "titleFirewall": "Firewall",
    "textFirewall": "Um sich mit dem Headset verbinden zu können, müssen Firewall-Regeln hinzugefügt werden. Das benötigt Administratoren-Rechte.",
    "buttonFirewall": "Firewall-Regeln hinzufügen",
    "buttonDriver": "ALVR-Treiber hinzufügen",
    "titleTracking": "Tracking",
    "textTracking": "Wie soll das Tracking der Controller gehandhabt werden.Wenn du planst schnelle Spiele wie Beatsaber zu spielen, wähle Mittel oder Schnell aus. Für langsamere Spiele wie Skyrim reicht die Einstellung Normal.",
    "normalTracking": "Normal",
    "mediumTracking": "Mittel",
    "fastTracking": "Schnell",
    "titlePerformance": "Performance Voreinstellung",
    "textPerformance": "Bitte wähle eine Voreinstellung aus, die zu deinem Setup passt. Das wird ein paar Einstellungen für dich erledigen.",
    "compatPerformance": "Kompatibilität",
    "qualityPerformance": "Visuelle Qualität",
    "titleFinished": "Fertiggestellt",
    "textFinished": "Du kannst dieses Setup immer wieder von dem \"Installation\" Tab auf der linken Seite ausführen",
    "buttonNext": "Weiter",
    "buttonClose": "Schließen",
    "driverFailed": "Treiber konnte nicht hinzugefügt werden",
    "driverSuccess": "Treiber erfolgreich hinzugefügt",
    "firewallFailed": "Firewall-Regel konnte nicht erstellt werden",
    "firewallSuccess": "Firewall-Regel erfolgreich erstellt"
});