define({
    "title": "Wilkommen zu ALVR",
    "subtitle": "Hier wirst du durchs Standard-Setup von ALVR geleitet",
    "titleHardwareReq": "Benötigte Hardware",
    "textHardwareReq": "ALVR benötigt eine dedicated und aktuelle Grafikkarte (Intel HD Graphics ist nicht unterstützt). Hier ist die <a target='_blank' href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>Liste von Unterstützen GPUs</a>. <br/> <br/> Stelle sicher, dass du mindestens ein Audio-Output-Gerät hast.",
    "titleSoftwareReq": "Benötigte Software",
    "textSoftwareReq": "Gehe sicher, dass du SteamVR installiert hast, mindestens einmal geöffnet, und danach geschlossen hast. <br/> <br/> Wenn du es noch nicht hast, bitte Installiere die aktuellste  <a  target='_blank' href='https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads'>Visual C++ Redistrubutable x64</a> Version. <br/> <br/> Um das Quest Mikrofon zu streamen musst du das <a  target='_blank' href='https://www.vb-audio.com/Cable/'>Virtual Audio Cable installieren</a>.",
    "titleFirewall": "Firewall",
    "textFirewall": "Um sich mit dem Headset verbinden zu können, müssen Firewall-Regeln hinzugefügt werden. Das benötigt Administratoren-Rechte.",
    "buttonFirewall": "Firewall-Regeln hinzufügen",
    "titleDriver": "Treiber",
    "textDriver": "Der ALVR Treiber muss mit SteamVR verbunden sein. Wenn existent, entferne jegliche störende Treiber. (Wenn du nicht weißt, was du zu tun hast, entferne alle Treiber, und füge dann den ALVR Treiber hinzu)",
    "buttonDriver": "ALVR-Treiber hinzufügen",
    "titleTracking": "Tracking",
    "textTracking": "Wie soll das Tracking der Controller gehandhabt werden.Wenn du planst schnelle Spiele wie Beatsaber zu spielen, wähle Mittel oder Schnell aus. Für langsamere Spiele wie Skyrim reicht die Einstellung Normal.",
    "normalTracking": "Normal",
    "mediumTracking": "Mittel",
    "fastTracking": "Schnell",
    "titlePerformance": "Performance Voreinstellung",
    "textPerformance": "Bitte wähle eine Voreinstellung aus, die zu deinem Setup passt. Das wird ein paar Einstellungen für dich erledigen.",
    "compatPerformance": "Kompatibilität",
    "qualityPerformance": "Visuelle Qualität",
    "titleFinished": "Fertiggestellt",
    "textFinished": "Du kannst dieses Setup immer wieder von dem \"Installation\" Tab auf der linken Seite ausführen",
    "buttonNext": "Weiter",
    "buttonClose": "Schließen",
    "driverFailed": "Treiber konnte nicht hinzugefügt werden",
    "driverSuccess": "Treiber erfolgreich hinzugefügt",
    "firewallFailed": "Firewall-Regel konnte nicht erstellt werden",
    "firewallSuccess": "Firewall-Regel erfolgreich erstellt"
});