define({
    "root": {
        "title": "ALVR",
        // Side bar
        "monitor": "Monitor",
        "settings": "Settings",
        "installation": "Installation",
        "about": "About",
        "languages": "Languages",
        "systemLanguage": "System",
        // Settings page
        "toggleAdvanced": "Show advanced options",
        "settingsGuide": "Settings guide",
        "restartSteamVR": "Restart SteamVR",
        // Installation page
        "runSetupWizard": "Run setup wizard",
        "addFirewallRules": "Add firewall rules",
        "removeFirewallRules": "Remove firewall rules",
        "firewallSuccess": "Firewall rules successfully set",
        // About page
        "aboutText": "Stream VR games from your PC to your headset via Wi-Fi. <br/> ALVR uses technologies like <a target= '_blank' href='https://developer.oculus.com/documentation/native/android/mobile-timewarp-overview/'>Asynchronous TimeWarp (ATW)</a> and <a target= '_blank' href='https://developer.oculus.com/documentation/native/android/mobile-ffr/'>Fixed Foveated Rendering (FFR)</a> for a smoother experience. <br/> All games that work with an Oculus Rift(s) should work with ALVR. <br/> This is a fork of ALVR that works with Oculus Quest and Go. <br/> <br/> Visit us on GitHub <a target= '_blank' href='https://github.com/alvr-org/ALVR/'>https://github.com/alvr-org/ALVR/</a> <br/> Join us on Discord: <a target='_blank' href='https://discord.gg/ALVR'>https://discord.gg/ALVR</a>",
        "checkForUpdates": "Check for updates",
        "noNeedForUpdate": "No update available",
        "needUpdateClickForMore": "Update available, click for more information",
        "updatePopupTitle": "Update Found!",
        "cancelUpdateButton": "Dismiss",
        "moreUpdateButton": "Website",
        "okUpdateButton": "Update",
    },
    "it": true,
    "sl": true,
    "es": true,
    "fr": true,
    "ja": true,
    "zh": true,
    "ru": true,
    "bg": true,
    "de": true,
    "nl": true,
    "ko": true,
});
