define({
    // Connection tab
    connection: "Connectie",
    // Clients container
    clients: "Clienten",
    newClients: "Nieuwe clienten",
    addTrustedClient: "Vertrouwen",
    trustedClients: "Vertrouwde clienten",
    removeTrustedClient: "Verwijder",
    troubleshooting: `Is er geen headset beschikbaar? Bezoek onze pagina voor probleemoplossing <a target= '_blank' href="https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset">hier</a>`,
    // Manually add client page
    manAddClient: "Client handmatig toevoegen",
    addClient: "Client toevoegen",
    deviceName: "Apparaat naam",
    deviceNameHelp: "Geef je headset een naam",
    clientHostname: "Hostnaam",
    clientHostnameHelp: "Zoals weergegeven bij het openen van de ALVR-client op uw apparaat",
    ipAddress: "IP adres",
    ipHelp: "Voer het exterene IP-adres van de headset toe",
    addClientButton: "Client toevoegen",
    //Configure client page
    configureClient: "Client configureren",
    configureClientButton: "Configureren",
    configureClientAddIp: "Nieuw IP adres toevoegen",
    configureClientRemoveIp: "Verwijderen",
    // Statistics container
    statistics: "Statistieken",
    streamingStatistics: "Streaming statistieken",
    totalPackets: "Totale pakketten",
    packetRate: "Pakketsnelheid",
    packetsLostTotal: "Totale pakketten verloren",
    packetsLostPerSecond: "Pakketten verloren / s",
    totalSent: "Totaal verzonden",
    sentRate: "Verzonden snelheid",
    totalLatency: "Totale latency",
    encodeLatency: "Codeer Latency",
    encodeLatencyMax: "Codeer latency maximaal",
    transportLatency: "Transport latency",
    decodeLatency: "Decodeer latency",
    fecPercentage: "Fec percentage",
    fecFailureTotal: "Totale mislukte Fec",
    fecFailureInSecond: "Fec mislukt / s",
    clientFPS: "Client FPS",
    serverFPS: "Server FPS",
    packets: "Pakketten",
    packetss: "Pakketten / s",
    // Logging tab
    logging: "Logboek",
    //validation errors
    error_DuplicateHostname: "Een toestel met deze hostnaam is al geregistreerd",
    error_DuplicateIp: "Dit IP adres is al geregistreerd op dit toestel",
    error_InvalidIp: "Geen geldig IPv4-adres",
    //Performance graphs tab
    performanceGraphs: "Performantie grafieken",
    performanceEncode: "Coderen",
    performanceDecode: "Decoderen",
    performanceTransport: "Transport",
    performanceOther: "Andere",
    performanceLatency: "Latency",
    performanceFramerate: "Framerate",
    performanceNoDateCaptured: "Nog geen gegevens vastgelegd",
});
