define({
    // Connection tab
    connection: "接続",
    // Clients container
    clients: "クライアント",
    newClients: "新しいクライアント",
    // "addTrustedClient": "",
    trustedClients: "信用済みクライアント",
    removeTrustedClient: "削除",
    // "troubleshooting": "",
    // Manually add client page
    manAddClient: "クライアントを手動で追加",
    addClient: "クライアントを追加",
    // "deviceName": "",
    // "deviceNameHelp": "",
    // "clientHostname": "",
    // "clientHostnameHelp": "",
    ipAddress: "IPアドレス",
    ipHelp: "ヘッドセットのIPアドレスを入力してください",
    addClientButton: "クライアントを追加",
    // Configure client page
    // "configureClient": "",
    // "configureClientButton": "",
    // "configureClientAddIp": "",
    // "configureClientRemoveIp": "",
    // Statistics container
    statistics: "統計情報",
    streamingStatistics: "ストリーミング統計情報",
    totalPackets: "総パケット数",
    packetRate: "パケット速度",
    packetsLostTotal: "総損失パケット数",
    packetsLostPerSecond: "損失パケット/s",
    totalSent: "総送信量",
    sentRate: "送信速度",
    totalLatency: "総レイテンシ",
    encodeLatency: "エンコードレイテンシ",
    encodeLatencyMax: "最大エンコードレイテンシ",
    transportLatency: "転送レイテンシ",
    decodeLatency: "デコードレイテンシ",
    fecPercentage: "前方誤り訂正(FEC)率",
    fecFailureTotal: "総損失FEC数",
    fecFailureInSecond: "損失FEC/s",
    clientFPS: "クライアントFPS",
    serverFPS: "サーバFPS",
    packets: "パケット",
    packetss: "パケット/s",
    // Logging tab
    logging: "ログ",
    // validation errors
    // "error_DuplicateHostname": "",
    // "error_DuplicateIp": "",
    // "error_InvalidIp": "",
    // Performance graphs tab
    // "performanceGraphs": "",
    // "performanceEncode": "",
    // "performanceDecode": "",
    // "performanceTransport": "",
    // "performanceOther": "",
    // "performanceLatency": "",
    // "performanceFramerate": "",
    // "performanceNoDateCaptured": "",
});
