define({
    "connection": "Връзка",
    "logging": "логване",
    "clients": "Клиенти",
    "newClients": "Нови клиенти",
    "trustedClients": "Одобрени клиенти",
    "manAddClient": "Добавете клиента ръчно",
    "removeTrustedClient": "Премахване",
    "statistics": "Потокова статистика",
    "addClient": "Добавете клиент",
    "ipAddress": "IP-Адрес",
    "ipHelp": "Въведете известния IP-Адрес на слушалките",
    "addClientButton": "Добавете клиент",
    "totalPackets": "Общo пакети",
    "packetRate": "Скорост на трансфер на пакети",
    "packetsLostTotal": "Общо загубени пакети",
    "packetsLostPerSecond": "Изгубени пакети/сек",
    "totalSent": "Общо изпратени",
    "sentRate": "Изпращане в секунда",
    "totalLatency": "Общо закъснение",
    "encodeLatency": "Закъснение на енкодера",
    "encodeLatencyMax": "Максимално закъснение на енкодера",
    "transportLatency": "Закъснение на предаването",
    "decodeLatency": "Закъснение на декодера",
    "fecPercentage": "Общ процент на корекция на грешки напред (FEC)",
    "fecFailureTotal": "Общо неуспех на FEC",
    "fecFailureInSecond": "FEC грешки/сек",
    "clientFPS": "FPS на клиента",
    "serverFPS": "FPS на сървъра",
    "packets": "пакети",
    "packetss": "пакети/сек"
});