define({
    // Connection tab
    connection: "Verbindung",
    // Clients container
    clients: "Clients",
    newClients: "Neue Clients",
    addTrustedClient: "Hinzufügen",
    trustedClients: "Vertraute Clients",
    removeTrustedClient: "Entfernen",
    troubleshooting: `Taucht dein Headset nicht auf? Folge <a target= '_blank' href="https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset">dieser</a> Hilfeseite (ENG)`,
    // Manually add client page
    manAddClient: "Manuelles hinzufügen eines Clients",
    addClient: "Client hinzufügen",
    deviceName: "Gerätename",
    deviceNameHelp: "Gib deinem Headset einen Namen",
    clientHostname: "Hostname",
    clientHostnameHelp: "Der Name, den du auf dem ALVR Client siehst",
    ipAddress: "IP-Addresse",
    ipHelp: "Gib die IP-Addresse deines Clients ein",
    addClientButton: "Client hinzufügen",
    // Configure client page
    configureClient: "Client konfigurieren",
    configureClientButton: "Konfigurieren",
    configureClientAddIp: "Neue IP-Addresse hinzufügen",
    configureClientRemoveIp: "Entfernen",
    // Statistics container
    statistics: "Statistiken",
    streamingStatistics: "Streaming Statistiken",
    totalPackets: "Alle Packets",
    packetRate: "Packetrate",
    packetsLostTotal: "Gesamter Packet-Verlust",
    packetsLostPerSecond: "Packets verloren pro sekunde",
    totalSent: "Alle gesendeten",
    sentRate: "Gesendete Rate",
    totalLatency: "Gesamte Verzögerung",
    encodeLatency: "Encodierungsverzögerung",
    encodeLatencyMax: "Maximale Encodierungsverzögerung",
    transportLatency: "Transportverzögerung",
    decodeLatency: "Entschlüsselungsverzögerung",
    fecPercentage: "Fec Prozentsatz",
    fecFailureTotal: "Fec Verlust gesamt",
    fecFailureInSecond: "Fec Verlust pro sekunde",
    clientFPS: "Client FPS",
    serverFPS: "Server FPS",
    packets: "Packets",
    packetss: "Packets/sek",
    // Logging tab
    logging: "Protokollierung",
    // Validation errors
    error_DuplicateHostname: "Es gibt bereits ein Gerät mit diesem Namen",
    error_DuplicateIp: "Diese IP-Addresse ist auf diesem Gerät bereits registriert",
    error_InvalidIp: "Dies ist keine Gültige IPv4-Addresse",
    // Performance graphs tab
    performanceGraphs: "Leistungsgraphen",
    performanceEncode: "Encodieren",
    performanceDecode: "Decodieren",
    performanceTransport: "Transport",
    performanceOther: "Sonstige",
    performanceLatency: "Latenz",
    performanceFramerate: "Bildwiederholrate (Hz)",
    performanceNoDateCaptured: "Noch keine Daten vorhanden",
});
