define({
    // Connection tab
    connection: "Връзка",
    // Clients container
    clients: "Клиенти",
    newClients: "Нови клиенти",
    // "addTrustedClient": "",
    trustedClients: "Одобрени клиенти",
    removeTrustedClient: "Премахване",
    // "troubleshooting": "",
    // Manually add client page
    manAddClient: "Добавете клиента ръчно",
    addClient: "Добавете клиент",
    // "deviceName": "",
    // "deviceNameHelp": "",
    // "clientHostname": "",
    // "clientHostnameHelp": "",
    ipAddress: "IP-Адрес",
    ipHelp: "Въведете известния IP-Адрес на слушалките",
    addClientButton: "Добавете клиент",
    // Configure client page
    // "configureClient": "",
    // "configureClientButton": "",
    // "configureClientAddIp": "",
    // "configureClientRemoveIp": "",
    // Statistics container
    statistics: "Cтатистика",
    streamingStatistics: "Потокова статистика",
    totalPackets: "Общo пакети",
    packetRate: "Скорост на трансфер на пакети",
    packetsLostTotal: "Общо загубени пакети",
    packetsLostPerSecond: "Изгубени пакети/сек",
    totalSent: "Общо изпратени",
    sentRate: "Изпращане в секунда",
    totalLatency: "Общо закъснение",
    encodeLatency: "Закъснение на енкодера",
    encodeLatencyMax: "Максимално закъснение на енкодера",
    transportLatency: "Закъснение на предаването",
    decodeLatency: "Закъснение на декодера",
    fecPercentage: "Общ процент на корекция на грешки напред (FEC)",
    fecFailureTotal: "Общо неуспех на FEC",
    fecFailureInSecond: "FEC грешки/сек",
    clientFPS: "FPS на клиента",
    serverFPS: "FPS на сървъра",
    packets: "пакети",
    packetss: "пакети/сек",
    // Logging tab
    logging: "логване",
    // validation errors
    // "error_DuplicateHostname": "",
    // "error_DuplicateIp": "",
    // "error_InvalidIp": "",
    // Performance graphs tab
    // "performanceGraphs": "",
    // "performanceEncode": "",
    // "performanceDecode": "",
    // "performanceTransport": "",
    // "performanceOther": "",
    // "performanceLatency": "",
    // "performanceFramerate": "",
    // "performanceNoDateCaptured": "",
});
