define({
    "root": {
        "registeredDrivers": "Registered Drivers",
        "noDrivers": "No Drives registered",
        "removeDriver": "remove",
        "driverUnregisterSuccessful": "Driver successfully unregistred",
        "driverUnregisterFailed": "Unregistering driver failed",
        "registerAlvrDriver": "Register ALVR driver",
        "registerAlvrDriverSuccess": "Driver successfully registered",
        "driverNotice": "IMPORTANT: Since ALVR v13.1.0, registering the driver is discouraged. Now the driver registration is needed only when you want to launch SteamVR by itself or when you want to use ALVR together with other SteamVR drivers, like <a href='https://www.driver4vr.com/'>Driver4VR</a> for full body tracking.",
    },
    "it": true,
    "es": true,
    "fr": true,
    "ja": true,
    "zh": true,
    "ru": true,
    "bg": true,
    "de": true,
});