define({
    "root": {
        "title": "ALVR",
        "monitor": "Monitor",
        "settings": "Settings",
        "installation": "Installation",
        "about": "About",
        "toggleAdvanced": "Show advanced options",
        "runSetupWizard": "Run setup wizard",
        "addFirewallRules": "Add firewall rules",
        "removeFirewallRules": "Remove firewall rules",
        "firewallSuccess": "Firewall rules successfully set",
        "restartSteamVR": "Restart SteamVR",
        "aboutText": "Stream VR games from your PC to your Oculus Quest via Wi-FI. <br/> ALVR uses technologies like Asynchronous Timewarp and Fixed Foveated Rendering for a smoother experience. <br/> All games that work with an Oculus Rift(s) should work with ALVR. <br/> This is a fork of ALVR that works only with Oculus Quest. <br/> <br/> Visit us on GitHub <a  href='https://github.com/JackD83/ALVR/'>https://github.com/JackD83/ALVR/</a> <br/> Join us on Discord: <a href='https://discord.com/invite/KbKk3UM'>https://discord.com/invite/KbKk3UM</a>",
        "checkForUpdates": "Check for updates",
        "noNeedForUpdate": "No need for update",
        "needUpdateClickForMore": "Need update, click for more information"
    },
    "it": true,
    "es": true,
    "fr": true,
    "ja": true,
    "zh": true,
    "ru": true,
    "bg": true,
    "de": true,
});