define({
    "root": {
        "connection": "Connection",
        "logging": "Logging",
        "clients": "Clients",
        "newClients": "New Clients",
        "trustedClients": "Trusted Clients",
        "manAddClient": "Manually add client",
        "removeTrustedClient": "remove",
        "statistics": "Streaming Statistics",
        "addClient": "Add client",
        "clientType": "Type",
        "ipAddress": "IP-Address",
        "ipHelp": "Enter know IP-address of the HMD",
        "addClientButton": "Add client",
        "totalPackets": "Total Packets",
        "packetRate": "PacketRate",
        "packetsLostTotal": "Total packets lost",
        "packetsLostPerSecond": "Packets lost/s",
        "totalSent": "Total sent",
        "sentRate": "Sent rate",
        "totalLatency": "Total latency",
        "encodeLatency": "Encoder Latency",
        "encodeLatencyMax": "Encode latency max",
        "transportLatency": "Transport latency",
        "decodeLatency": "Decoder latency",
        "fecPercentage": "Fec percentage",
        "fecFailureTotal": "Fec failure total",
        "fecFailureInSecond": "Fec failure / s",
        "clientFPS": "Client fps",
        "serverFPS": "Server fps",
        "packets": "Packets",
        "packetss": "Packets/s",
        "troubleshooting": `Is your headset not showing up? Visit our troubleshooting page <a  target='_blank' href="https://github.com/JackD83/ALVR/wiki/Troubleshooting-(for-ALVR-12.0.0-and-later)#alvr-cant-see-my-headset">here</a>`
    },
    "it": true,
    "es": true,
    "fr": true,
    "ja": true,
    "zh": true,
    "ru": true,
    "de": true,
});