define({
    "root": {
        // Connection tab
        "connection": "Connection",
        // Clients container
        "clients": "Clients",
        "newClients": "New Clients",
        "addTrustedClient": "Trust",
        "trustedClients": "Trusted Clients",
        "removeTrustedClient": "Remove",
       // Manually add client page
        "manAddClient": "Manually add client",
        "addClient": "Add client",
        "clientType": "Type",
        "deviceName": "Device name",
        "deviceNameHelp": "Give your HMD a name",
        "clientHostname": "Hostname",
        "clientHostnameHelp": "As displayed when opening the ALVR client on your device",
        "ipAddress": "IP-Address",
        "ipHelp": "Enter IP-address of the HMD",
        "addClientButton": "Add client",
        "troubleshooting": `Is your headset not showing up? Visit our troubleshooting page <a href="https://github.com/alvr-org/ALVR/wiki/Troubleshooting-(for-ALVR-12.0.0-and-later)#alvr-cant-see-my-headset">here</a>`,
        //Configure client page
        "configureClient": "Configure client",
        "configureClientButton": "Configure",
        "configureClientAddIp": "Add new IP",
        // Statistics container
        "statistics": "Statistics",
        "streamingStatistics": "Streaming Statistics",
        "totalPackets": "Total Packets",
        "packetRate": "PacketRate",
        "packetsLostTotal": "Total packets lost",
        "packetsLostPerSecond": "Packets lost / s",
        "totalSent": "Total sent",
        "sentRate": "Sent rate",
        "totalLatency": "Total latency",
        "encodeLatency": "Encoder Latency",
        "encodeLatencyMax": "Encode latency max",
        "transportLatency": "Transport latency",
        "decodeLatency": "Decoder latency",
        "fecPercentage": "Fec percentage",
        "fecFailureTotal": "Fec failure total",
        "fecFailureInSecond": "Fec failure / s",
        "clientFPS": "Client FPS",
        "serverFPS": "Server FPS",
        "packets": "Packets",
        "packetss": "Packets / s",
        // Logging tab
        "logging": "Logging",
        //validation errors        
        "error_DuplicateHostname": "A device with this hostname is already registered",
        "error_InvalidIp": "Not a valid IP v4 formatted address",
        //Performance graphs tab
        "performanceGraphs": "Performance graphs",
        "performanceEncode": "Encode",
        "performanceDecode": "Decode",
        "performanceTransport": "Transport",
        "performanceOther": "Other",
        "performanceLatency": "Latency",
        "performanceFramerate": "Framerate",
        "performanceNoDateCaptured": "No data captured yet",
    },
    "it": true,
    "es": true,
    "fr": true,
    "ja": true,
    "zh": true,
    "ru": true,
    "bg": true,
    "de": true,
});