define({
    "root": {
        "_root_video_tab.name": "Video",
        "_root_video_tab.description": "Video settings",
        "_root_audio_tab.name": "Audio",
        "_root_audio_tab.description": "Audio settings",
        "_root_headset_tab.name": "Headset",
        "_root_connection_tab.name": "Connection",
        "_root_debug_tab.name": "Debug",
        "_root_video_adapterIndex.name": "Adapter Index",
        "_root_video_adapterIndex.description": "System index of GPU-Adapter",
        "_root_video_refreshRate.name": "Display Refreshrate",
        "_root_video_refreshRate.description": "Refreshrate used on the HMD",
        "_root_video_encodeBitrateMbs.name": "Video Bitrate",
        "_root_video_encodeBitrateMbs.description": "The bitrate of the encoded video",
        "_root_video_force60hz.name": "Force 60hz Mode",
        "_root_video_force60hz.description": "Forces the refreshrate to 60Hz",
        "_root_video_renderResolution.name": "Video resolution settings",
        "_root_video_renderResolution.description": "The video resolution to use",
        "_root_video_recommendedTargetResolution.name": "Target Resolution",
        "_root_video_recommendedTargetResolution.description": "The target video resolution to use",
        "_root_video_resolutionDropdown.name": "Video resolution",
        "_root_video_resolutionDropdown.description": "Scale for the used video resolution",
        "_root_video_renderResolution-choice-.name": "Video resolution",
        "_root_video_renderResolution_scale-choice-.name": "use video scale",
        "_root_video_renderResolution_scale-choice-.description": "Scale factor for the video resolution",
        "_root_video_renderResolution_scale.name": "Scale",
        "_root_video_renderResolution_scale.description": "The video scale",
        "_root_video_renderResolution_absolute-choice-.name": "use absolute video resolution",
        "_root_video_renderResolution_absolute-choice-.description": "Use absolute video resolution",
        "_root_video_renderResolution_absolute_absolute.name": "Absolute resolution",
        "_root_video_renderResolution_absolute_absolute.description": "The absolute resolution",
        "_root_video_renderResolution_absolute_width.name": "Video width",
        "_root_video_renderResolution_absolute_width.description": "The width of the encoded video",
        "_root_video_renderResolution_absolute_height.name": "Video height",
        "_root_video_renderResolution_absolute_height.description": "The height of the encoded video",
        "_root_video_recommendedTargetResolution-choice-.name": "Video target resolution",
        "_root_video_recommendedTargetResolution-choice-.description": "UNCLEAR!!",
        "_root_video_recommendedTargetResolution_scale-choice-.name": "use target resolution scale",
        "_root_video_recommendedTargetResolution_scale.name": "Scale",
        "_root_video_recommendedTargetResolution_scale.description": "UNCLEAR!!",
        "_root_video_recommendedTargetResolution_absolute-choice-.name": "use absolute target resolution",
        "_root_video_recommendedTargetResolution_absolute_absolute.name": "Absolute target resolution",
        "_root_video_recommendedTargetResolution_absolute_width.name": "Video width",
        "_root_video_recommendedTargetResolution_absolute_width.description": "The width of the encoded video",
        "_root_video_recommendedTargetResolution_absolute_height.name": "Video height",
        "_root_video_recommendedTargetResolution_absolute_height.description": "The height of the encoded video",
        "_root_video_eyeFov.name": "Eye Fov",
        "_root_video_eyeFov.description": "The eye field of view",
        "_root_video_eyeFov_0_eyeFov_0.name": "Left eye",
        "_root_video_eyeFov_0_eyeFov_0.description": "The settings for the left eye",
        "_root_video_eyeFov_0_left.name": "left",
        "_root_video_eyeFov_0_left.description": "left value",
        "_root_video_eyeFov_0_right.name": "right",
        "_root_video_eyeFov_0_right.description": "right value",
        "_root_video_eyeFov_0_top.name": "top",
        "_root_video_eyeFov_0_top.description": "top value",
        "_root_video_eyeFov_0_bottom.name": "bottom",
        "_root_video_eyeFov_0_bottom.description": "bottom value",
        "_root_video_eyeFov_1_eyeFov_1.name": "Right eye",
        "_root_video_eyeFov_1_eyeFov_1.description": "the settings for the right eye",
        "_root_video_eyeFov_1_left.name": "left",
        "_root_video_eyeFov_1_left.description": "left value",
        "_root_video_eyeFov_1_right.name": "right",
        "_root_video_eyeFov_1_right.description": "right value",
        "_root_video_eyeFov_1_top.name": "top",
        "_root_video_eyeFov_1_top.description": "top value",
        "_root_video_eyeFov_1_bottom.name": "bottom",
        "_root_video_eyeFov_1_bottom.description": "bottom value",
        "_root_video_secondsFromVsyncToPhotons.name": "Seconds from Vsync to photons",
        "_root_video_secondsFromVsyncToPhotons.description": "Time from vsync event to light generated by the display",
        "_root_video_ipd.name": "Interpupillary distance",
        "_root_video_ipd.description": "Space between the eyes",
        "_root_video_foveatedRendering.name": "Foveated rendering",
        "_root_video_foveatedRendering.description": "Settings for foveated rendering. Renders the edges of the visible area with less resolution",
        "_root_video_foveatedRendering_enabled.name": "enable",
        "_root_video_foveatedRendering_enabled.description": "Enables the foveated rendering",
        "_root_video_foveatedRendering_content_strength.name": "strength",
        "_root_video_foveatedRendering_content_strength.description": "Defines how strong the foveated rendering shoul be",
        "_root_video_foveatedRendering_content_shape.name": "Shape",
        "_root_video_foveatedRendering_content_shape.description": "The shape of the foveated rendering",
        "_root_video_foveatedRendering_content_verticalOffset.name": "Vertical offset",
        "_root_video_foveatedRendering_content_verticalOffset.description": "Defines if the effect should be stronger at the bottom or the top",
        "_root_video_colorCorrection.name": "Color correction",
        "_root_video_colorCorrection.description": "The color correction",
        "_root_video_colorCorrection_enabled.name": "Enable",
        "_root_video_colorCorrection_enabled.description": "Enables the color correction",
        "_root_video_colorCorrection_content_brightness.name": "Brightness",
        "_root_video_colorCorrection_content_brightness.description": "Adjusts the brightness",
        "_root_video_colorCorrection_content_contrast.name": "Contrast",
        "_root_video_colorCorrection_content_contrast.description": "Adjusts the contrast",
        "_root_video_colorCorrection_content_saturation.name": "Saturation",
        "_root_video_colorCorrection_content_saturation.description": "Adjusts the saturation",
        "_root_video_colorCorrection_content_gamma.name": "Gamma",
        "_root_video_colorCorrection_content_gamma.description": "Adjusts the gamma value",
        "_root_video_colorCorrection_content_sharpening.name": "Sharpening",
        "_root_video_colorCorrection_content_sharpening.description": "Sharpens the image",
        "_root_video_codec-choice-.name": "Video Codec",
        "_root_video_codec-choice-.description": "The video codec to use",
        "_root_video_codec_H264.name": "h264",
        "_root_video_codec_H264.description": "Use the H264 Codec",
        "_root_video_codec_H264-choice-.name": "H264",
        "_root_video_codec_H264-choice-.description": "Use the h264 codec",
        "_root_video_codec_HEVC-choice-.name": "HEVC (h265)",
        "_root_video_codec_HEVC-choice-.description": "Use the HEVC (h265) codec",
        "_root_audio_gameAudio.name": "Stream game audio",
        "_root_audio_gameAudio.description": "Stream game audio to the HDM",
        "_root_audio_gameAudio_enabled.name": "unused",
        "_root_audio_gameAudio_enabled.description": "unused",
        "_root_audio_gameAudio_content_deviceDropdown.name": "Select audio device",
        "_root_audio_gameAudio_content_deviceDropdown.description": "unused",
        "_root_audio_gameAudio_content_device.name": "Used audio device",
        "_root_audio_gameAudio_content_device.description": "Used audio device for streaming",
        "_root_audio_microphone.name": "Stream microphone",
        "_root_audio_microphone.description": "Streams the HMD microphone",
        "_root_headset_serialNumber.name": "",
        "_root_headset_serialNumber.description": "",
        "_root_headset_trackingSystemName.name": "",
        "_root_headset_trackingSystemName.description": "",
        "_root_headset_modelNumber.name": "",
        "_root_headset_modelNumber.description": "",
        "_root_headset_driverVersion.name": "",
        "_root_headset_driverVersion.description": "",
        "_root_headset_manufacturerName.name": "",
        "_root_headset_manufacturerName.description": "",
        "_root_headset_renderModelName.name": "",
        "_root_headset_renderModelName.description": "",
        "_root_headset_registeredDeviceType.name": "",
        "_root_headset_registeredDeviceType.description": "",
        "_root_headset_trackingFrameOffset.name": "",
        "_root_headset_trackingFrameOffset.description": "",
        "_root_headset_positionOffset.name": "",
        "_root_headset_positionOffset.description": "",
        "_root_headset_positionOffset_0.name": "",
        "_root_headset_positionOffset_0.description": "",
        "_root_headset_positionOffset_1.name": "",
        "_root_headset_positionOffset_1.description": "",
        "_root_headset_positionOffset_2.name": "",
        "_root_headset_positionOffset_2.description": "",
        "_root_headset_useTrackingReference.name": "",
        "_root_headset_useTrackingReference.description": "",
        "_root_headset_force3dof.name": "",
        "_root_headset_force3dof.description": "",
        "_root_headset_controllers.name": "",
        "_root_headset_controllers.description": "",
        "_root_headset_controllers_enabled.name": "",
        "_root_headset_controllers_enabled.description": "",
        "_root_headset_controllers_content_trackingSystemName.name": "",
        "_root_headset_controllers_content_trackingSystemName.description": "",
        "_root_headset_controllers_content_manufacturerName.name": "",
        "_root_headset_controllers_content_manufacturerName.description": "",
        "_root_headset_controllers_content_modelNumber.name": "",
        "_root_headset_controllers_content_modelNumber.description": "",
        "_root_headset_controllers_content_renderModelNameLeft.name": "",
        "_root_headset_controllers_content_renderModelNameLeft.description": "",
        "_root_headset_controllers_content_renderModelNameRight.name": "",
        "_root_headset_controllers_content_renderModelNameRight.description": "",
        "_root_headset_controllers_content_serialNumber.name": "",
        "_root_headset_controllers_content_serialNumber.description": "",
        "_root_headset_controllers_content_ctrlType.name": "",
        "_root_headset_controllers_content_ctrlType.description": "",
        "_root_headset_controllers_content_registeredDeviceType.name": "",
        "_root_headset_controllers_content_registeredDeviceType.description": "",
        "_root_headset_controllers_content_inputProfilePath.name": "",
        "_root_headset_controllers_content_inputProfilePath.description": "",
        "_root_headset_controllers_content_triggerMode.name": "",
        "_root_headset_controllers_content_triggerMode.description": "",
        "_root_headset_controllers_content_trackpadClickMode.name": "",
        "_root_headset_controllers_content_trackpadClickMode.description": "",
        "_root_headset_controllers_content_trackpadTouchMode.name": "",
        "_root_headset_controllers_content_trackpadTouchMode.description": "",
        "_root_headset_controllers_content_backMode.name": "",
        "_root_headset_controllers_content_backMode.description": "",
        "_root_headset_controllers_content_recenterButton.name": "",
        "_root_headset_controllers_content_recenterButton.description": "",
        "_root_headset_controllers_content_poseTimeOffset.name": "",
        "_root_headset_controllers_content_poseTimeOffset.description": "",
        "_root_headset_controllers_content_positionOffsetLeft.name": "",
        "_root_headset_controllers_content_positionOffsetLeft.description": "",
        "_root_headset_controllers_content_positionOffsetLeft_0.name": "",
        "_root_headset_controllers_content_positionOffsetLeft_0.description": "",
        "_root_headset_controllers_content_positionOffsetLeft_1.name": "",
        "_root_headset_controllers_content_positionOffsetLeft_1.description": "",
        "_root_headset_controllers_content_positionOffsetLeft_2.name": "",
        "_root_headset_controllers_content_positionOffsetLeft_2.description": "",
        "_root_headset_controllers_content_rotationOffsetLeft.name": "",
        "_root_headset_controllers_content_rotationOffsetLeft.description": "",
        "_root_headset_controllers_content_rotationOffsetLeft_0.name": "",
        "_root_headset_controllers_content_rotationOffsetLeft_0.description": "",
        "_root_headset_controllers_content_rotationOffsetLeft_1.name": "",
        "_root_headset_controllers_content_rotationOffsetLeft_1.description": "",
        "_root_headset_controllers_content_rotationOffsetLeft_2.name": "",
        "_root_headset_controllers_content_rotationOffsetLeft_2.description": "",
        "_root_headset_controllers_content_hapticsIntensity.name": "",
        "_root_headset_controllers_content_hapticsIntensity.description": "",
        "_root_headset_controllers_content_modeIdx.name": "",
        "_root_headset_controllers_content_modeIdx.description": "",
        "_root_connection_listenHost.name": "",
        "_root_connection_listenHost.description": "",
        "_root_connection_listenPort.name": "",
        "_root_connection_listenPort.description": "",
        "_root_connection_controlHost.name": "",
        "_root_connection_controlHost.description": "",
        "_root_connection_controlPort.name": "",
        "_root_connection_controlPort.description": "",
        "_root_connection_throttlingBitrateMbs.name": "",
        "_root_connection_throttlingBitrateMbs.description": "",
        "_root_connection_sendingTimeslotUs.name": "",
        "_root_connection_sendingTimeslotUs.description": "",
        "_root_connection_limitTimeslotPackets.name": "",
        "_root_connection_limitTimeslotPackets.description": "",
        "_root_connection_clientRecvBufferSize.name": "",
        "_root_connection_clientRecvBufferSize.description": "",
        "_root_connection_frameQueueSize.name": "",
        "_root_connection_frameQueueSize.description": "",
        "_root_connection_aggressiveKeyframeResend.name": "",
        "_root_connection_aggressiveKeyframeResend.description": "",
        "_root_debug_log.name": "",
        "_root_debug_log.description": "",


    },
    "de-de": true
});