define({
    "root": {
        "_root_video_tab.name": "Video",
        "_root_video_tab.description": "Video settings",
        "_root_audio_tab.name": "Audio",
        "_root_audio_tab.description": "Audio settings",
        "_root_headset_tab.name" : "Headset",
        "_root_connection_tab.name" : "Connection",
        "_root_debug_tab.name" : "Debug",
        "_root_video_adapterIndex.name": "Adapter Index",
        "_root_video_adapterIndex.description": "System index of GPU-Adapter",
        "_root_video_refreshRate.name": "Display Refreshrate",
        "_root_video_refreshRate.description": "Refreshrate used on the HMD",
        "_root_video_encodeBitrateMbs.name": "Video Bitrate",
        "_root_video_encodeBitrateMbs.description": "The bitrate of the encoded video",
        "_root_video_force60hz.name": "Force 60hz Mode",
        "_root_video_force60hz.description": "Forces the refreshrate to 60Hz",
        "_root_video_renderResolution.name": "Video resolution settings",
        "_root_video_renderResolution.description": "The video resolution to use",
        "_root_video_recommendedTargetResolution.name": "Target Resolution",
        "_root_video_recommendedTargetResolution.description": "The target video resolution to use",
        "_root_video_resolutionDropdown.name" :"Video resolution",
        "_root_video_resolutionDropdown.description" : "Scale for the used video resolution",
        "_root_video_renderResolution_scale-choice-.name": "use video scale",
        "_root_video_renderResolution_scale-choice-.description": "Scale factor for the video resolution",
        "_root_video_renderResolution_scale.name": "Scale",
        "_root_video_renderResolution_scale.description": "The video scale",
        "_root_video_renderResolution_absolute-choice-.name": "use absolute video resolution",
        "_root_video_renderResolution_absolute-choice-.description": "Use absolute video resolution",
        "_root_video_renderResolution_absolute_absolute.name": "Absolute resolution",
        "_root_video_renderResolution_absolute_absolute.description": "The absolute resolution",
        "_root_video_renderResolution_absolute_width.name" : "Video width",
        "_root_video_renderResolution_absolute_width.description" : "The width of the encoded video",
        "_root_video_renderResolution_absolute_height.name" : "Video height",
        "_root_video_renderResolution_absolute_height.description" : "The height of the encoded video",

    },
    "de-de": true
});