define({
    "root": {
        "title": "Welcome to ALVR",
        "subtitle": "This wizard will guide you to the basic setup of ALVR",
        "titleFirewall": "Firewall",
        "textFirewall": "To communicate with the headset, some firewall rules need to be set.This requires administrator rights.",
        "buttonFirewall" : "Add firewall rules",
        "titleDriver": "Driver",
        "textDriver"  : "The ALVR driver needs to be registered with SteamVR",
        "buttonDriver" : "Register driver",
        "titleTracking" : "Tracking",
        "textTracking" : "How should the tracking of the controller be handled.If you plan on playing fast paced games like Beatsaber, choose medium or fast. For slower games like Skyrim leave it on normal.",
        "normalTracking" : "normal",
        "mediumTracking" :"medium",
        "fastTracking" : "fast",
        "titlePerformance" : "Performance preset",
        "textPerformance" : "Please choose preset that fits your setup. This will adjust some settings for you.",
        "compatPerformance" :"compatibility",
        "perfPerformance" : "performance",
        "titleFinished": "Finished",
        "textFinished":"You can always restart this wizard from the \"Installation\" tab on the left",
        "buttonNext" :"Next",
        "buttonClose" :"Close",
        "driverFailed" :"Registering driver failed",
        "driverSuccess" :"Driver successfully registered",
        "firewallFailed" : "Setting firewall rules failed",
        "firewallSuccess" : "Firewall rules successfully set"
    },
    "it-it": true,
    "de-de": false
});