define({
    "root": {
        "title": "Welcome to ALVR",
        "subtitle": "This wizard will guide you to the basic setup of ALVR",
        "titleHardwareReq": "Hardware requirements",
        "textHardwareReq": "ALVR requires a dedicated and recent graphics card (Intel HD graphics is not supported). Here is the <a target='_blank' href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>list of supported GPUs</a>. <br/> <br/> Make sure you have at least one output audio device.",
        "titleSoftwareReq": "Software requirements",
        "textSoftwareReq": "Make sure you installed SteamVR, launched it at least once and then closed it. <br/> <br/> If you didn't already, please install the latest <a  target='_blank' href='https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads'>Visual C++ Redistrubutable x64</a> package. <br/> <br/> To stream the Quest microphone you need to install the <a  target='_blank' href='https://www.vb-audio.com/Cable/'>Virtual Audio Cable</a>.",
        "titleFirewall": "Firewall",
        "textFirewall": "To communicate with the headset, some firewall rules need to be set. This requires administrator rights.",
        "buttonFirewall": "Add firewall rules",
        "titleDriver": "Driver",
        "textDriver": "The ALVR driver needs to be registered with SteamVR. If present, remove any other interfering driver. (If you don't know what to do, remove all drivers, then register ALVR driver)",
        "buttonDriver": "Register ALVR driver",
        "titleTracking": "Tracking",
        "textTracking": "How should the tracking of the controller be handled.If you plan on playing fast paced games like Beatsaber, choose medium or fast. For slower games like Skyrim leave it on normal.",
        "normalTracking": "Normal",
        "mediumTracking": "Medium",
        "fastTracking": "Fast",
        "titlePerformance": "Performance preset",
        "textPerformance": "Please choose preset that fits your setup. This will adjust some settings for you.",
        "compatPerformance": "Compatibility",
        "qualityPerformance": "Visual quality",
        "titleFinished": "Finished",
        "textFinished": "You can always restart this wizard from the \"Installation\" tab on the left",
        "buttonNext": "Next",
        "buttonClose": "Close",
        "driverFailed": "Registering driver failed",
        "driverSuccess": "Driver successfully registered",
        "firewallFailed": "Setting firewall rules failed",
        "firewallSuccess": "Firewall rules successfully set"
    },
    "it": true,
    "es": true,
    "fr": true,
    "ja": true,
    "zh": true,
    "ru": true,
    "de-de": false
});