define({
    // Connection tab
    connection: "客户端连接",
    // Clients container
    clients: "客户端",
    newClients: "可连接的新客户端",
    // "addTrustedClient": "",
    trustedClients: "已信任的客户端",
    // "removeTrustedClient": "",
    troubleshooting:
        "你的头显没有显示在这里？访问我们的<a target= '_blank' href='https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset'>Github问题解决页面</a>以获得帮助。",
    // Manually add client page
    manAddClient: "手动添加客户端",
    addClient: "添加客户端",
    // "deviceName": "",
    // "deviceNameHelp": "",
    // "clientHostname": "",
    // "clientHostnameHelp": "",
    ipAddress: "IP地址",
    ipHelp: "添加已知的头显IP地址",
    addClientButton: "添加客户端",
    // Configure client page
    // "configureClient": "",
    // "configureClientButton": "",
    // "configureClientAddIp": "",
    // "configureClientRemoveIp": "",
    // Statistics container
    statistics: "状态信息",
    streamingStatistics: "串流状态信息",
    totalPackets: "数据包总数",
    packetRate: "封包速率",
    packetsLostTotal: "丢包数",
    packetsLostPerSecond: "每秒丢失数据包数",
    totalSent: "已发送流量",
    sentRate: "网络速度",
    totalLatency: "总延迟",
    encodeLatency: "编码延迟",
    encodeLatencyMax: "最高编码延迟",
    transportLatency: "传输延迟",
    decodeLatency: "解码延迟",
    fecPercentage: "Fec 百分比",
    fecFailureTotal: "Fec 总丢失数据包数",
    fecFailureInSecond: "Fec 每秒丢失数据包数",
    clientFPS: "客户端帧数",
    serverFPS: "服务端帧数",
    packets: "个数据包",
    packetss: "个数据包每秒",
    // Logging tab
    logging: "日志记录",
    // validation errors
    // "error_DuplicateHostname": "",
    // "error_DuplicateIp": "",
    // "error_InvalidIp": "",
    // Performance graphs tab
    // "performanceGraphs": "",
    // "performanceEncode": "",
    // "performanceDecode": "",
    // "performanceTransport": "",
    // "performanceOther": "",
    // "performanceLatency": "",
    // "performanceFramerate": "",
    // "performanceNoDateCaptured": "",
});
