#ifndef ALVRCLIENT_PACKETTYPES_H
#define ALVRCLIENT_PACKETTYPES_H
#include <stdint.h>
#include <assert.h>
#include "../alvr_server/bindings.h"

enum ALVR_CODEC {
	ALVR_CODEC_H264 = 0,
	ALVR_CODEC_H265 = 1,
};

enum ALVR_RATE_CONTROL_METHOD {
	ALVR_CBR = 0,
	ALVR_VBR = 1,
};

enum ALVR_ENTROPY_CODING {
	ALVR_CABAC = 0,
	ALVR_CAVLC = 1,
};

enum ALVR_ENCODER_QUALITY_PRESET {
	ALVR_QUALITY = 0,
	ALVR_BALANCED = 1,
	ALVR_SPEED = 2
};

enum ALVR_INPUT {
	ALVR_INPUT_SYSTEM_CLICK,
	ALVR_INPUT_APPLICATION_MENU_CLICK,
	ALVR_INPUT_GRIP_CLICK,
	ALVR_INPUT_GRIP_VALUE,
	ALVR_INPUT_GRIP_TOUCH,
	ALVR_INPUT_A_CLICK,
	ALVR_INPUT_A_TOUCH,
	ALVR_INPUT_B_CLICK,
	ALVR_INPUT_B_TOUCH,
	ALVR_INPUT_X_CLICK,
	ALVR_INPUT_X_TOUCH,
	ALVR_INPUT_Y_CLICK,
	ALVR_INPUT_Y_TOUCH,
	ALVR_INPUT_JOYSTICK_CLICK,
	ALVR_INPUT_JOYSTICK_X,
	ALVR_INPUT_JOYSTICK_Y,
	ALVR_INPUT_JOYSTICK_TOUCH,
	ALVR_INPUT_BACK_CLICK,
	ALVR_INPUT_GUIDE_CLICK,
	ALVR_INPUT_START_CLICK,
	ALVR_INPUT_TRIGGER_CLICK,
	ALVR_INPUT_TRIGGER_VALUE,
	ALVR_INPUT_TRIGGER_TOUCH,
	ALVR_INPUT_TRACKPAD_X,
	ALVR_INPUT_TRACKPAD_Y,
	ALVR_INPUT_TRACKPAD_CLICK,
	ALVR_INPUT_TRACKPAD_TOUCH,
	ALVR_INPUT_THUMB_REST_TOUCH,

	ALVR_INPUT_FINGER_INDEX,
	ALVR_INPUT_FINGER_MIDDLE,
	ALVR_INPUT_FINGER_RING,
	ALVR_INPUT_FINGER_PINKY,
	ALVR_INPUT_GRIP_FORCE,
	ALVR_INPUT_TRACKPAD_FORCE,

	ALVR_INPUT_MAX = ALVR_INPUT_TRACKPAD_FORCE,
	ALVR_INPUT_COUNT = ALVR_INPUT_MAX + 1
};
#define ALVR_BUTTON_FLAG(input) (1ULL << input)

#endif //ALVRCLIENT_PACKETTYPES_H
