define({
    "connection": "Connexion",
    "logging": "Logs",
    "clients": "Client",
    "newClients": "Nouveau client",
    "trustedClients": "Client approuvés",
    "manAddClient": "Ajouter un client manuellment",
    "removeTrustedClient": "Retirer",
    "statistics": "Statistiques de streaming",
    "addClient": "Ajouter client",
    "ipAddress": "Adresse IP",
    "ipHelp": "Entrez l'adresse IP connue du casque",
    "addClientButton": "Ajouter client",
    "totalPackets": "Paquets totaux",
    "packetRate": "Taux de paquets",
    "packetsLostTotal": "Paquets perdus totaux",
    "packetsLostPerSecond": "Paquets perdus par seconde",
    "totalSent": "Total envoyé",
    "sentRate": "Taux d'envoi",
    "totalLatency": "Latence totale",
    "encodeLatency": "Latence de l'encodeur",
    "encodeLatencyMax": "Latence maximale de l'encodeur",
    "transportLatency": "Latence de transmission",
    "decodeLatency": "Latence du décodeur",
    "fecPercentage": "pourcentage de correction d'erreur directe (FEC)",
    "fecFailureTotal": "Total d'erreur FEC",
    "fecFailureInSecond": "Erreurs FEC par seconde",
    "clientFPS": "FPS du client",
    "serverFPS": "FPS du serveur",
    "packets" : "Paquets",
    "packetss" : "Paquets par seconde"
});