define({
    "customVideoScale": "Personalizzato",
    "_root_video_tab.name": "Video",
    "_root_video_tab.description": "Impostazioni video",
    "_root_audio_tab.name": "Audio",
    "_root_audio_tab.description": "Impostazioni audio",
    "_root_headset_tab.name": "Casque",
    "_root_connection_tab.name": "Connexion",
    "_root_extra_tab.name": "Extra",
	
    "_root_video_encodeBitrateMbs.name": "Bitrate video",
    "_root_video_encodeBitrateMbs.description": "Bitrate du streaming video.30Mbps est recommandé. \nUn bitrate plus élevé donne une meilleure image mais rajoute de la latence ainsi que du traffic réseau.",
    "_root_video_force60hz.name": "Forcer le 60Hz",
    "_root_video_force60hz.description": "Foce la video a 60 FPS",
    "_root_video_resolutionDropdown.name": "Résolution video",
    "_root_video_resolutionDropdown.description": `100% correspond a la résolution native de 2880x1600 de l'Oculus Quest.
    Augmenter la résolution peut améliorer la qualité visuelle, mais ce n'est pas recommandé.
    Une résolution en dessous de 100% peut réduire la latence et améliorer la performance du reseau `,
    "_root_video_renderResolution-choice-.name": "Résolution video",
    "_root_video_foveatedRendering.name": "Rendu fovéal",
    "_root_video_foveatedRendering.description": "Paramètres du rendu fovéal, technique de rendu qui réduit la résolution de la vision périphérique",
    "_root_video_foveatedRendering_enabled.name": "Activer",
    "_root_video_foveatedRendering_enabled.description": `Technique de rendu qui réduit la résolution de la vision périphérique. cela permet de réduire la résolution de la vidéo transmise par le réseau pour réduire la latence. en fonction des paramètres il y aura plus ou moins d'artéfacts sur le bord de l'image `,
    "_root_video_foveatedRendering_content_strength.name": "Intensité",
    "_root_video_foveatedRendering_content_strength.description": "Une intensité plus élevé donne moins de détails sur les bords de l'image et plus d'artéfacts",
    "_root_video_foveatedRendering_content_verticalOffset.name": "Décalage vertical",
    "_root_video_foveatedRendering_content_verticalOffset.description": "une plus haute valeaur décale verticalement la zone ou la qualité sera plus haute.",
    "_root_video_colorCorrection.name": "Correction de couleurs",
    "_root_video_colorCorrection.description": "Corrections de couleurs",
    "_root_video_colorCorrection_enabled.name": "Activer",
    "_root_video_colorCorrection_enabled.description": "Les changements sont appliqués dans cet ordre : Sharpening, Gamma, Luminosité, Contraste, Saturation. ",
    "_root_video_colorCorrection_content_brightness.name": "Luminosité",
    "_root_video_colorCorrection_content_brightness.description": "Luminosité: -1 donne une image noire et 1 donne une image blanche",
    "_root_video_colorCorrection_content_contrast.name": "Contraste",
    "_root_video_colorCorrection_content_contrast.description": "Contraste: -1 donne une image grise",
    "_root_video_colorCorrection_content_saturation.name": "Saturation",
    "_root_video_colorCorrection_content_saturation.description": "Saturation: -1 donne une image en noir et blanc",
    "_root_video_colorCorrection_content_gamma.name": "Gamma",
    "_root_video_colorCorrection_content_gamma.description": "Gamma",
    "_root_video_colorCorrection_content_sharpening.name": "Sharpening",
    "_root_video_colorCorrection_content_sharpening.description": "Sharpening: -1 est le plus flou et 5 est le plus net",
    "_root_video_codec-choice-.name": "Codec video",
    "_root_video_codec-choice-.description": "Si posible utilisez h265 pour une meilleure qualité visuel avec un bitrate plus bas",
    "_root_video_codec_H264-choice-.name": "h264",
    "_root_video_codec_H264-choice-.description": "Utiliser le codec h264",
    "_root_video_codec_HEVC-choice-.name": "HEVC (h265)",
    "_root_video_codec_HEVC-choice-.description": "Utiliser le codec HEVC (h265)",

    "_root_audio_gameAudio.name": "Transmettre l'audio au casque",
    "_root_audio_gameAudio.description": "Transmet l'audio sur le casque",
    "_root_audio_gameAudio_enabled.name": "unused",
    "_root_audio_gameAudio_enabled.description": "Permet de streamer l'audio du jeu sur le casque",
    "_root_audio_gameAudio_content_deviceDropdown.name": "Choisisez la source audio",
    "_root_audio_gameAudio_content_deviceDropdown.description": "Source audio utilisé pour la capture",
    "_root_audio_microphone.name": "Transmettre le microphone",
    "_root_audio_microphone.description": "Permet d'utiliser le microphone du casque sur l'ordinateur",

    "_root_headset_trackingFrameOffset.name": "Décalage temporel du tracking",
    "_root_headset_trackingFrameOffset.description": "Décalage temporel du tracking pour l'algorithme de prédiction",
    "_root_headset_force3dof.name": "Forcer le tracking 3DOF",
    "_root_headset_force3dof.description": "Force le tracking sur trois axes",
    "_root_headset_controllers.name": "Controleurs",
    "_root_headset_controllers.description": "unused",
    "_root_headset_controllers_enabled.name": "Activer",
    "_root_headset_controllers_enabled.description": "Activer l'utilisation des controleurs",
    "_root_headset_controllers_content_hapticsIntensity.name": "Intensité des vibrations",
    "_root_headset_controllers_content_hapticsIntensity.description": "Facteur d'intensité du retour haptique",
    "_root_headset_headsetEmulationMode.name": "Mode d'émulation du casque",
    "_root_headset_headsetEmulationMode.description": "Permet de choisir quel casque émuler pour plus de compatibilité",
    "_root_headset_controllers_content_controllerMode.name": "Mode d'émulation des controleurs",
    "_root_headset_controllers_content_controllerMode.description": "Permet de choisir quel controleurs émuler pour plus de compatibilité ou pour activer le suivi des mains",
    "_root_headset_controllers_content_poseTimeOffset.name": "Pose time offset",
    "_root_headset_controllers_content_poseTimeOffset.description": "Décalage pour l'algorithme de prédiction de pose",

    "_root_connection_bufferOffset.name": "Décalage du buffer",
    "_root_connection_bufferOffset.description": "décalage pour augmenter ou réduire la taille du buffer client. Le décalage du buffer ne peut être négatif.",	
    "_root_connection_aggressiveKeyframeResend.name": "Renvoi de keyframes aggresif",
    "_root_connection_aggressiveKeyframeResend.description": `Réduit l'intervale minimum entre les keyframes de 100ms a 5ms, utilisé seulment quand des pertes de paquets sont détéctés. améliore l'experience sur des réseaux avec pertes de paquets`,
    "_root_connection_disableThrottling.name": "Désactive le throttling",
    "_root_connection_disableThrottling.description": "Désactive le throttling, envoie les données le plus vite possible.",
    "_root_connection_suppressFrameDrop.name": "Eviter la perte de paquets",
    "_root_connection_suppressFrameDrop.description": "Essaye d'éviter la perte de paquets",

    "_root_extra_revertConfirmDialog.name": "Confirmer remise a zéro",
    "_root_extra_revertConfirmDialog.description": "Demande une confirmations avant de remettre une valeur a zéro",
    "_root_extra_restartConfirmDialog.name": "Confirmer redémarrer SteamVR",
    "_root_extra_restartConfirmDialog.description": "Demande une confirmation avant de redémarrer SteamVR.",
});