define({
    "title": "Bienvenue sur ALVR",
    "subtitle": "Cet assistant va vous aider pour la configuration de base d'ALVR",
    "titleHardwareReq": "Matériel requis",
    "textHardwareReq": "ALVR nécésite une carte graphique dédié et recente (Intel HD graphics non supporté). Voici une <a href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>liste de GPU supporté</a>. <br/> <br/> Assurez vous d'avoir au moins une sortie audio.",
    "titleSoftwareReq": "Logiciels requis",
    "textSoftwareReq": "Pour transemettre l'audio du microphone veuillez installer <a  href='https://www.vb-audio.com/Cable/'>VB-Audio Virtual Cable</a>.",
    "titleFirewall": "Pare-feu",
    "textFirewall": "Pour communiquer avec le casque, quelques règles de pare-feu doivent etre ajoutés. Cela nécésite les droits administrateur.",
    "buttonFirewall" : "Ajouter règles de pare-feu",
    "titleTracking" : "Suivi",
    "textTracking" : `Comment doit être le suivi des controlleurs. Si vous prévoyez de jouer a des jeux rapides tels que Beatsaber, choisez Moyen ou Rapide. Pour des jeux plus lents tels que Skyrim laissez le en Normal.`,
    "normalTracking" : "Normal",
    "mediumTracking" :"Moyen",
    "fastTracking" : "Rapide",
    "titlePerformance" : "Préréglages de performance",
    "textPerformance" : "Choisisez le réglage qui correspond a votre ordinateur. Cela va ajuster quelques reglages pour vous.",
    "compatPerformance" :"Compatibilité",
    "qualityPerformance" : "Qualité visuelle",
    "titleFinished": "Fini",
    "textFinished":`Vous pouvez toujours recommencer cet assistant depuis la catégorie "Installation" a gauche`,
    "buttonNext" :"Suivant",
    "buttonClose" :"Fermer",
    "driverFailed" :"Le driver n'a pas pu s'enregistrer",
    "driverSuccess" :"Le driver s'est bien enregistrer",
    "firewallFailed" : "Erreur d'ajout des règles du pare-feu",
    "firewallSuccess" : "Règles du pare-feu ajouté avec succes"
});