define({
    "title": "Bienvenue sur ALVR",
    "subtitle": "Cet assistant va vous aider pour la configuration de base d'ALVR",
    "titleHardwareReq": "Matériel requis",
    "textHardwareReq": "ALVR nécésite une carte graphique dédié et recente (Intel HD graphics non supporté). Voici une <a target='_blank' href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>liste de GPU supporté</a>. <br/> <br/> Assurez vous d'avoir au moins une sortie audio.",
    "titleSoftwareReq": "Logiciels requis",
    "textSoftwareReq": "Assurez vous d'avoir installé SteamVR, et de l'avoir lancé au moins une fois. <br/> <br/> Si vous ne l'avez pas deja fait, veuillez installer la derniere version de <a  target='_blank' href='https://support.microsoft.com/fr-fr/help/2977003/the-latest-supported-visual-c-downloads'>Visual C++ Redistrubutable x64</a>. <br/> <br/> Pour transemettre l'audio du microphone veuillez installer <a  target='_blank' href='https://www.vb-audio.com/Cable/'>Cable audio virtuel</a>.",
    "titleFirewall": "Pare-feu",
    "textFirewall": "Pour communiquer avec le casque, quelques règles de pare-feu doivent etre ajoutés. Cela nécésite les droits administrateur.",
    "buttonFirewall" : "Ajouter règles de pare-feu",
    "titleDriver": "Driver",
    "textDriver"  : "Les drivers d'ALVR doivent ètre enregistré avec SteamVR. Si présentes, veuillez retirer tout autre driver intérferrant. (Si vous ne savez pas quoi faire, retirez tout les drivers puis ajoutez celui d'ALVR)",
    "buttonDriver" : "Enregistrer le driver d'ALVR",
    "titleTracking" : "Suivi",
    "textTracking" : `Comment doit être le suivi des controlleurs. Si vous prévoyez de jouer a des jeux rapides tels que Beatsaber, choisez Moyen ou Rapide. Pour des jeux plus lents tels que Skyrim laissez le en Normal.`,
    "normalTracking" : "Normal",
    "mediumTracking" :"Moyen",
    "fastTracking" : "Rapide",
    "titlePerformance" : "Préréglages de performance",
    "textPerformance" : "Choisisez le réglage qui correspond a votre ordinateur. Cela va ajuster quelques reglages pour vous.",
    "compatPerformance" :"Compatibilité",
    "qualityPerformance" : "Qualité visuelle",
    "titleFinished": "Fini",
    "textFinished":`Vous pouvez toujours recommencer cet assistant depuis la catégorie "Installation" a gauche`,
    "buttonNext" :"Suivant",
    "buttonClose" :"Fermer",
    "driverFailed" :"Le driver n'a pas pu s'enregistrer",
    "driverSuccess" :"Le driver s'est bien enregistrer",
    "firewallFailed" : "Erreur d'ajout des règles du pare-feu",
    "firewallSuccess" : "Règles du pare-feu ajouté avec succes"
});