define({
    "title": "Benvenuto su ALVR",
    "subtitle": "Questa guida ti aiuterà ad installare e configurare ALVR",
    "titleSoftwareReq": "Requisiti software",
    "textSoftwareReq": "Controlla di aver installato SteamVR e di averlo avviato almeno una volta e poi chiuso. <br/> Se non l'hai già fatto, installa l'ultimo pacchetto <a  target='_blank' href='https://support.microsoft.com/it-it/help/2977003/the-latest-supported-visual-c-downloads'>Visual C++ Redistrubutable x64</a>.",
    "titleFirewall": "Firewall",
    "textFirewall": "Per comunicare con il visore, devono essere impostate alcune eccezioni del firewall. Questo richiede privilegi di amministratore.",
    "buttonFirewall" : "Aggiungi eccezione firewall",
    "titleDriver": "Driver",
    "textDriver"  : "Il driver di ALVR deve essere registrato su SteamVR. Se presenti, rimuovi gli altri driver che interferiscono. (Se non sai cosa fare, rimuovi tutti i driver e poi registra il driver di ALVR)",
    "buttonDriver" : "Registra driver di ALVR",
    "titleTracking" : "Tracking",
    "textTracking" : `Scegli la modalità di tracking dei controller. Giochi frenetici come BeatSaber richiedono la modalità "veloce". Per giochi più tranquilli come Skyrim, scegli "medio" o "lento".`,
    "normalTracking" : "Lento",
    "mediumTracking" :"Medio",
    "fastTracking" : "Veloce",
    "titlePerformance" : "Impostazioni per la performance",
    "textPerformance" : "Scegli la modalità più adatta al tuo PC. Verrano impostati alcuni valori in automatico.",
    "compatPerformance" :"Compatibilità",
    "qualityPerformance" : "Qualità visuale",
    "titleFinished": "Finito",
    "textFinished":`Potrai ricomiciare questa guida dalla sezione "Installazione" a sinistra`,
    "buttonNext" :"Avanti",
    "buttonClose" :"Chiudi",
    "driverFailed" :"Registrazione del driver Fallita",
    "driverSuccess" :"Driver registrato con successo",
    "firewallFailed" : "Errore durante l'aggiunta dell'eccezione del firewall",
    "firewallSuccess" : "Eccezione del firewall impostata con successo"
});