define({
    "title": "Benvenuto su ALVR",
    "subtitle": "Questa guida ti aiuterà ad installare e configurare ALVR",
    "titleHardwareReq": "Requisiti hardware",
    "textHardwareReq": "ALVR richiede una scheda grafica dedicata e recente. <br/> <br/> Controlla di avere almeno un dispositivo audio di output. <br/> <br/>",
    "titleSoftwareReq": "Requisiti software",
    "textSoftwareReq": "Per trasmettere l'audio del microfono del visore devi installare <a  href='https://www.vb-audio.com/Cable/'>VB-Audio Virtual Cable</a>.",
    "titleFirewall": "Firewall",
    "textFirewall": "Per comunicare con il visore, devono essere impostate alcune eccezioni del firewall. Questo richiede privilegi di amministratore.",
    "buttonFirewall": "Aggiungi eccezione firewall",
    "buttonDriver": "Registra driver di ALVR",
    "titleTracking": "Tracking",
    "textTracking": `Scegli la modalità di tracking dei controller. Giochi frenetici come BeatSaber richiedono la modalità "veloce". Per giochi più tranquilli come Skyrim, scegli "medio" o "lento".`,
    "normalTracking": "Lento",
    "mediumTracking": "Medio",
    "fastTracking": "Veloce",
    "titlePerformance": "Impostazioni per la performance",
    "textPerformance": "Scegli la modalità più adatta al tuo PC. Verrano impostati alcuni valori in automatico.",
    "compatPerformance": "Compatibilità",
    "qualityPerformance": "Qualità visuale",
    "titleFinished": "Finito",
    "textFinished": `Potrai ricomiciare questa guida dalla sezione "Installazione" a sinistra`,
    "buttonNext": "Avanti",
    "buttonClose": "Chiudi",
    "driverFailed": "Registrazione del driver Fallita",
    "driverSuccess": "Driver registrato con successo",
    "firewallFailed": "Errore durante l'aggiunta dell'eccezione del firewall",
    "firewallSuccess": "Eccezione del firewall impostata con successo",
    "YourGPUIs": "La tua GPU:",
    "GPUSupported": "\nQuesta GPU è probabilmente supportata",
    "GPUUnsupported": "\nQuesta GPU potrebbe non essere supportata. Puoi comunque provare ALVR per vedere se funziona",
});