define({
    // Connection tab
    connection: "Connexion",
    // Clients container
    clients: "Client",
    newClients: "Nouveau client",
    addTrustedClient: "Ajouter",
    trustedClients: "Client approuvés",
    removeTrustedClient: "Retirer",
    troubleshooting:
        "Votre casque n'apparait pas dans la liste ? Visitez note page de support <a target= '_blank' href='https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset'>ici</a>",
    // Manually add client page
    manAddClient: "Ajouter un client manuellement",
    addClient: "Ajouter client",
    deviceName: "Nom du casque",
    deviceNameHelp: "Donnez au casque un nom",
    clientHostname: "Nom d'hôte",
    clientHostnameHelp: "Le même que celui affiché sur votre casque quand le client est lancé",
    ipAddress: "Adresse IP",
    ipHelp: "Entrez l'adresse IP connue du casque",
    addClientButton: "Ajouter client",
    // Configure client page
    configureClient: "Configuration du client",
    configureClientButton: "Configurer",
    configureClientAddIp: "Ajouter une adresse IP",
    configureClientRemoveIp: "Supprimer",
    // Statistics container
    statistics: "Statistiques",
    streamingStatistics: "Statistiques de streaming",
    totalPackets: "Paquets totaux",
    packetRate: "Taux de paquets",
    packetsLostTotal: "Paquets perdus totaux",
    packetsLostPerSecond: "Paquets perdus par seconde",
    totalSent: "Total envoyé",
    sentRate: "Taux d'envoi",
    totalLatency: "Latence totale",
    encodeLatency: "Latence de l'encodeur",
    encodeLatencyMax: "Latence maximale de l'encodeur",
    transportLatency: "Latence de transmission",
    decodeLatency: "Latence du décodeur",
    fecPercentage: "pourcentage de correction d'erreur directe (FEC)",
    fecFailureTotal: "Total d'erreur FEC",
    fecFailureInSecond: "Erreurs FEC par seconde",
    clientFPS: "FPS du client",
    serverFPS: "FPS du serveur",
    packets: "Paquets",
    packetss: "Paquets par seconde",
    // Logging tab
    logging: "Logs",
    // validation errors
    error_DuplicateHostname: "Ce nom d'hôte est déjà utilisé par un autre casque.",
    error_DuplicateIp: "Cette addresse IP est déjà utilisé par un autre casque.",
    error_InvalidIp: "Cette addresse IP n'est par valide.",
    // Performance graphs tab
    performanceGraphs: "Graphiques",
    performanceEncode: "Encodeur",
    performanceDecode: "Décodeur",
    performanceTransport: "Transport",
    performanceOther: "Autre",
    performanceLatency: "Latence",
    performanceFramerate: "Fréquence d'images",
    performanceNoDateCaptured: "Aucune donnée capturée pour le moment",
});
