define({
    root: {
        // Connection tab
        connection: "Connection",
        // Clients container
        clients: "Clients",
        newClients: "New Clients",
        addTrustedClient: "Trust",
        trustedClients: "Trusted Clients",
        removeTrustedClient: "Remove",
        troubleshooting:
            "Is your headset not showing up? Visit our troubleshooting page <a target= '_blank' href='https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset'>here</a>",
        // Manually add client page
        manAddClient: "Add client manually",
        addClient: "Add client",
        deviceName: "Device name",
        deviceNameHelp: "Give your headset a name",
        clientHostname: "Hostname",
        clientHostnameHelp: "As displayed when opening the ALVR client on your device",
        ipAddress: "IP address",
        ipHelp: "Enter the remote IP address of the headset",
        addClientButton: "Add client",
        // Configure client page
        configureClient: "Configure client",
        configureClientButton: "Configure",
        configureClientAddIp: "Add new IP",
        configureClientRemoveIp: "Remove",
        // Statistics container
        statistics: "Statistics",
        streamingStatistics: "Streaming Statistics",
        totalPackets: "Total Packets",
        packetRate: "PacketRate",
        packetsLostTotal: "Total packets lost",
        packetsLostPerSecond: "Packets lost / s",
        totalSent: "Total sent",
        sentRate: "Sent rate",
        bitrate: "Bitrate",
        ping: "Ping",
        totalLatency: "Total latency",
        encodeLatency: "Encoder Latency",
        encodeLatencyMax: "Encode latency max",
        transportLatency: "Transport latency",
        decodeLatency: "Decoder latency",
        fecPercentage: "Fec percentage",
        fecFailureTotal: "Fec failure total",
        fecFailureInSecond: "Fec failure / s",
        clientFPS: "Client FPS",
        serverFPS: "Server FPS",
        packets: "Packets",
        packetss: "Packets / s",
        batteries: "Batteries",
        headset: "Headset",
        left: "Left",
        right: "Right",
        // Logging tab
        logging: "Logging",
        // validation errors
        error_DuplicateHostname: "A device with this hostname is already registered",
        error_DuplicateIp: "This IP address is already registed on this device",
        error_InvalidIp: "Not a valid IPv4 formatted address",
        // Performance graphs tab
        performanceGraphs: "Performance graphs",
        performanceNetwork: "Network",
        performanceReceive: "Receive",
        performanceSend: "Send",
        performanceRender: "Render",
        performanceIdle: "Idle",
        performanceTranscode: "Transcode",
        performanceEncode: "Encode",
        performanceDecode: "Decode",
        performanceTransport: "Transport",
        performanceClientIdle: "Client Idle",
        performanceOther: "Other",
        performanceLatency: "Latency",
        performanceTotalLatency: "Total Latency",
        performanceFramerate: "Framerate",
        performanceServer: "Server",
        performanceClient: "Client",
        performanceNoDateCaptured: "No data captured yet",
    },
    it: true,
    sl: true,
    es: true,
    fr: true,
    ja: true,
    zh: true,
    ru: true,
    bg: true,
    de: true,
    nl: true,
    ko: true,
});
