[package]
name = "alvr_system_info"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alvr_common.workspace = true

jni = "0.21"
local-ip-address = "0.6"

[target.'cfg(target_os = "android")'.dependencies]
ndk = { version = "0.9", features = ["api-level-26", "media"] }
ndk-context = "0.1"
ndk-sys = "0.6"
