define({
    // Connection tab
    connection: "연결",
    // Clients container
    clients: "클라이언트",
    newClients: "새로운 클라이언트",
    addTrustedClient: "신뢰하기",
    trustedClients: "신뢰한 클라이언트",
    removeTrustedClient: "제거하기",
    troubleshooting:
        "당신의 헤드셋이 보이지 않나요? 문제해결 페이지에 방문하세요 <a target= '_blank' href='https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset'>이곳</a>",
    // Manually add client page
    manAddClient: "수동으로 클라이언트 추가하기",
    addClient: "클라이언트 추가",
    deviceName: "기기 이름",
    deviceNameHelp: "헤드셋 이름을 입력하세요.",
    clientHostname: "호스트 이름",
    clientHostnameHelp: "ALVR 클라이언트를 실행했을때 표시됩니다.",
    ipAddress: "IP주소",
    ipHelp: "헤드셋 IP 주소를 입력하세요",
    addClientButton: "클라이언트 추가하기",
    // Configure client page
    configureClient: "클라이언트 설정",
    configureClientButton: "설정하기",
    configureClientAddIp: "새로운 IP 추가하기",
    configureClientRemoveIp: "제거하기",
    // Statistics container
    statistics: "상태",
    streamingStatistics: "전송 상태",
    totalPackets: "총 패킷",
    packetRate: "패킷 속도",
    packetsLostTotal: "총 손실 패킷",
    packetsLostPerSecond: "손실 패킷 / s",
    totalSent: "총 전송 용량",
    sentRate: "전송 속도",
    totalLatency: "총 지연시간",
    encodeLatency: "인코더 지연시간",
    encodeLatencyMax: "최대 인코드 지연시간",
    transportLatency: "전송 지연시간",
    decodeLatency: "디코더 지연시간",
    fecPercentage: "전진 에러 수정(Fec)률",
    fecFailureTotal: "총 Fec 실패",
    fecFailureInSecond: "Fec 실패 / s",
    clientFPS: "클라이언트 FPS",
    serverFPS: "서버 FPS",
    packets: "패킷",
    packetss: "패킷 / s",
    // Logging tab
    logging: "로그",
    // validation errors
    error_DuplicateHostname: "이미 등록된 호스트 이름입니다.",
    error_DuplicateIp: "이미 등록된 IP 주소입니다.",
    error_InvalidIp: "존재하지 않는 IPv4 주소입니다.",
    // Performance graphs tab
    performanceGraphs: "성능 그래프",
    performanceEncode: "인코드",
    performanceDecode: "디코드",
    performanceTransport: "전송",
    performanceOther: "기타",
    performanceLatency: "지연시간",
    performanceFramerate: "프레임률",
    performanceNoDateCaptured: "아직 데이터가 없습니다.",
});
