define({
    "connection": "接続",
    "logging": "ログ",
    "clients": "クライアント",
    "newClients": "新しいクライアント",
    "trustedClients": "信用済みクライアント",
    "manAddClient": "クライアントを手動で追加",
    "removeTrustedClient": "削除",
    "statistics": "ストリーミング統計情報",
    "addClient": "クライアントを追加",
    "ipAddress": "IPアドレス",
    "ipHelp": "HMDのIPアドレスを入力してください",
    "addClientButton": "クライアントを追加",
    "totalPackets": "総パケット数",
    "packetRate": "パケット速度",
    "packetsLostTotal": "総損失パケット数",
    "packetsLostPerSecond": "損失パケット/s",
    "totalSent": "総送信量",
    "sentRate": "送信速度",
    "totalLatency": "総レイテンシ",
    "encodeLatency": "エンコードレイテンシ",
    "encodeLatencyMax": "最大エンコードレイテンシ",
    "transportLatency": "転送レイテンシ",
    "decodeLatency": "デコードレイテンシ",
    "fecPercentage": "前方誤り訂正(FEC)率",
    "fecFailureTotal": "総損失FEC数",
    "fecFailureInSecond": "損失FEC/s",
    "clientFPS": "クライアントFPS",
    "serverFPS": "サーバFPS",
    "packets" : "パケット",
    "packetss" : "パケット/s"
});