define({
    "customVideoScale": "カスタム解像度",
    "_root_video_tab.name": "映像",
    "_root_video_tab.description": "映像設定",
    "_root_audio_tab.name": "音声",
    "_root_audio_tab.description": "音声設定",
    "_root_headset_tab.name": "HMD",
    "_root_connection_tab.name": "接続",
    "_root_extra_tab.name": "その他",
	
    "_root_video_encodeBitrateMbs.name": "映像ビットレート",
    "_root_video_encodeBitrateMbs.description": "映像ストリーミングのビットレート. 30Mbpsを推奨. \nビットレートを高くすると画質が良くなるが, レイテンシと通信量が多くなる",
    "_root_video_force60hz.name": "60Hzに強制",
    "_root_video_force60hz.description": "リフレッシュレートを60Hzに強制する",
    "_root_video_resolutionDropdown.name": "解像度",
    "_root_video_resolutionDropdown.description": `100%に設定するとOculus Questのネイティブ解像度である2880x1600になる.
    解像度を設定すると, 見た目の品質が多少向上する可能性があるが非推奨.
    100%より低く設定するとレイテンシが低下し, ネットワークパフォーマンスが向上する可能性がある`,
    "_root_video_renderResolution-choice-.name": "解像度",
    "_root_video_foveatedRendering.name": "フォービエイテッドレンダリング",
    "_root_video_foveatedRendering.description": "フォービエイテッドレンダリングに関する設定. 可視領域のエッジを低解像度で描画する",
    "_root_video_foveatedRendering_enabled.name": "有効化",
    "_root_video_foveatedRendering_enabled.description": `画像の中心部を高解像度で描画し, 周辺部を低解像度で描画する技術. これにより, ネットワーク経由で送信するビデオ解像度が大幅に減少する. 同ビットレートにおいて, 解像度が低い方がよりディテールを保持できると同時にレイテンシを低下させることができる. しかし, 設定やゲームによっては表示領域の端で多かれ少なかれ視覚的な異常を引き起こす`,
    "_root_video_foveatedRendering_content_strength.name": "強度",
    "_root_video_foveatedRendering_content_strength.description": "値が高いほど, より画像端付近の解像度が低くなり, 歪みが多くなる",
    "_root_video_foveatedRendering_content_verticalOffset.name": "垂直オフセット",
    "_root_video_foveatedRendering_content_verticalOffset.description": "値が高いほど, 高解像度の領域が下へ移動する",
    "_root_video_colorCorrection.name": "色補正",
    "_root_video_colorCorrection.description": "色の補正",
    "_root_video_colorCorrection_enabled.name": "有効化",
    "_root_video_colorCorrection_enabled.description": "色補正はシャープネス, ガンマ, 明度, コントラスト, 彩度の順に適用",
    "_root_video_colorCorrection_content_brightness.name": "明度",
    "_root_video_colorCorrection_content_brightness.description": "明るさ. -1設定時は完全に黒, 1設定時は完全に白となる",
    "_root_video_colorCorrection_content_contrast.name": "コントラスト",
    "_root_video_colorCorrection_content_contrast.description": "コントラスト. -1設定時はグレースケールとなる",
    "_root_video_colorCorrection_content_saturation.name": "彩度",
    "_root_video_colorCorrection_content_saturation.description": "鮮やかさ. -1設定時は白と黒となる",
    "_root_video_colorCorrection_content_gamma.name": "ガンマ",
    "_root_video_colorCorrection_content_gamma.description": "ガンマ値. sRGBからRGB空間に補正する場合は2.2を指定",
    "_root_video_colorCorrection_content_sharpening.name": "シャープネス",
    "_root_video_colorCorrection_content_sharpening.description": "鮮明化度. -1設定時は最も不鮮明で, 5設定時は最も鮮明化される",
    "_root_video_codec-choice-.name": "ビデオコーデック",
    "_root_video_codec-choice-.description": "使用されるビデオコーデック. 可能であれば, 低いビットレートでより見た目の品質が向上するH.265を推奨",
    "_root_video_codec_H264-choice-.name": "H.264",
    "_root_video_codec_H264-choice-.description": "H.264コーデックを使用する",
    "_root_video_codec_HEVC-choice-.name": "HEVC (H.265)",
    "_root_video_codec_HEVC-choice-.description": "HEVC (H.265)コーデックを使用する",

    "_root_audio_gameAudio.name": "ゲーム音声のストリーミング",
    "_root_audio_gameAudio.description": "ゲームの音声をHMDにストリーミングする",
    "_root_audio_gameAudio_enabled.name": "有効化",
    "_root_audio_gameAudio_enabled.description": "HMDへのゲーム音声のストリーミングを有効化する",
    "_root_audio_gameAudio_content_deviceDropdown.name": "オーディオ機器の選択",
    "_root_audio_gameAudio_content_deviceDropdown.description": "音声キャプチャのために使用されるオーディオ機器",
    "_root_audio_microphone.name": "マイクのストリーミング",
    "_root_audio_microphone.description": "HMDのマイクをストリーミングする",

    "_root_headset_trackingFrameOffset.name": "トラッキングフレームオフセット",
    "_root_headset_trackingFrameOffset.description": "姿勢予測アルゴリズム用のオフセット値",
    "_root_headset_force3dof.name": "3DoFに強制",
    "_root_headset_force3dof.description": "強制的に3軸自由度モードにする",
    "_root_headset_controllers.name": "コントローラ",
    "_root_headset_controllers.description": "unused",
    "_root_headset_controllers_enabled.name": "有効化",
    "_root_headset_controllers_enabled.description": "コントローラの使用を有効にする",
    "_root_headset_controllers_content_hapticsIntensity.name": "振動の強さ",
    "_root_headset_controllers_content_hapticsIntensity.description": "触覚フィードバックの強度",
    "_root_headset_headsetEmulationMode.name": "HMDエミュレーション",
    "_root_headset_headsetEmulationMode.description": "互換性向上のために様々なHMDをエミュレートする",
    "_root_headset_controllers_content_controllerMode.name": "コントローラエミュレーション",
    "_root_headset_controllers_content_controllerMode.description": "互換性向上のために様々なコントローラをエミュレートしたり, ハンドトラッキングを有効にする",
    "_root_headset_controllers_content_poseTimeOffset.name": "ポーズタイムオフセット",
    "_root_headset_controllers_content_poseTimeOffset.description": "姿勢予測アルゴリズム用のオフセット値",

    "_root_connection_bufferOffset.name": "バッファオフセット",
    "_root_connection_bufferOffset.description": "算出されたクライアントのバッファサイズを増減するオフセット. クライアントバッファを負の値にすることは不可",	
    "_root_connection_aggressiveKeyframeResend.name": "積極的キーフレーム再送",
    "_root_connection_aggressiveKeyframeResend.description": `キーフレーム間の最小間隔を100msから5msに減少させる. パケットロスが検出された場合にのみ使用され, パケットロスのあるネットワークでの使用感を改善する`,
    "_root_connection_disableThrottling.name": "スロットリングの無効化",
    "_root_connection_disableThrottling.description": "スロットリングを無効化し, データを出来る限り早く送信する",
    "_root_connection_suppressFrameDrop.name": "ドロップフレームの抑制",
    "_root_connection_suppressFrameDrop.description": "フレームのコマ落ちを抑制する",

    "_root_extra_revertConfirmDialog.name": "初期化の確認ダイアログ",
    "_root_extra_revertConfirmDialog.description": "設定値をデフォルトの値に戻す前に確認を求める",
    "_root_extra_restartConfirmDialog.name": "再起動の確認ダイアログ",
    "_root_extra_restartConfirmDialog.description": "SteamVRを再起動する前に確認求める",
});