define({
    "title": "ALVRへようこそ",
    "subtitle": "このウィザードではALVRの基本的な設定方法を説明します",
    "titleHardwareReq": "ハードウェア要件",
    "textHardwareReq": "ALVRには高性能なグラフィックボードが必要です（CPU内蔵のIntel HD Graphicsには対応していません）. サポートされているGPUの一覧は<a target='_blank' href='https://github.com/polygraphene/ALVR/wiki/Supported-GPU'>こちら</a>に記載しています. <br/> <br/> また, 少なくとも1つのオーディオ出力機器があることを確認してください.",
    "titleSoftwareReq": "ソフトウェア要件",
    "textSoftwareReq": "SteamVRをインストールし, 1度起動してから閉じてください. <br/> <br/> <a  target='_blank' href='https://support.microsoft.com/ja-jp/help/2977003/the-latest-supported-visual-c-downloads'>Visual C++ Redistrubutable x64</a>のインストールも必要です. <br/> <br/> Oculus Questのマイクをストリーミングするには<a  target='_blank' href='https://www.vb-audio.com/Cable/'>Virtual Audio Cable</a>もインストールしてください.",
    "titleFirewall": "ファイアウォール",
    "textFirewall": "ヘッドセットと通信するためにはファイアウォールの設定が必要です. この操作には管理者権限を要します.",
    "buttonFirewall" : "ファイアウォール設定を追加",
    "titleDriver": "ドライバ",
    "textDriver"  : "ALVRドライバをSteamVRに登録する必要があります. 干渉するドライバがあればすべて削除してください（よく分からない場合は, 既存のドライバをすべて削除してから登録してください）.",
    "buttonDriver" : "ALVRドライバを登録",
    "titleTracking" : "トラッキング",
    "textTracking" : "コントローラのトラッキング頻度を設定します. Beat Saberのような動きの速いゲームをプレイする場合は中速か高速を, Skyrimのような遅めのゲームの場合は普通を選んでください.",
    "normalTracking" : "普通",
    "mediumTracking" :"中速",
    "fastTracking" : "高速",
    "titlePerformance" : "パフォーマンス",
    "textPerformance" : "あなたの設定に合ったプリセットを選んでください. これにより, いくつかの設定が調整されます.",
    "compatPerformance" : "互換性重視",
    "qualityPerformance" : "見栄え重視",
    "titleFinished": "完了",
    "textFinished": "このウィザードは, 左側の\"インストール\"タブからいつでもやり直すことができます.",
    "buttonNext" :"次へ",
    "buttonClose" :"閉じる",
    "driverFailed" :"ドライバの登録に失敗しました",
    "driverSuccess" :"ドライバの登録が完了しました",
    "firewallFailed" : "ファイアウォールの設定に失敗しました",
    "firewallSuccess" : "ファイアウォールの設定が完了しました"
});