define({
    // Connection tab
    connection: "NAPRAVE",
    // Clients container
    clients: "Povezane naprave",
    newClients: "Nove naprave",
    addTrustedClient: "ZAUPAJ",
    trustedClients: "Poznane naprave",
    removeTrustedClient: "ODSTRANI",
    // Manually add client page
    manAddClient: "DODAJ NAPRAVO",
    addClient: "Dodaj napravo",
    clientType: "Vrsta",
    deviceName: "Ime naprave",
    deviceNameHelp: "Poimenuj svojo napravo",
    clientHostname: "Ime strežnika",
    clientHostnameHelp: "Kot prikazano ko odpreš ALVR na svoji napravi",
    ipAddress: "IP-Naslov",
    ipHelp: "Vnesi IP-Naslov svoje naprave",
    addClientButton: "DODAJ NAPRAVO",
    troubleshooting: `Se vaša naprava ne prikaže? Obiščite našo spletno stran za reševanje težav <a target= '_blank' href="https://github.com/alvr-org/ALVR/wiki/Troubleshooting-(for-ALVR-12.0.0-and-later)#alvr-cant-see-my-headset">tukaj</a>`,
    //Configure client page
    configureClient: "Nastavi napravo",
    configureClientButton: "IZBERI",
    configureClientAddIp: "DODAJ NOV IP",
    // Statistics container
    statistics: "PODROBNOSTI",
    streamingStatistics: "Podrobnosti prenosa",
    totalPackets: "Vsi zabojčki",
    packetRate: "Tok zabojčkov",
    packetsLostTotal: "Izgubljeni zabojčki",
    packetsLostPerSecond: "Izguba zabojčkov/sek",
    totalSent: "Poslani podatki",
    sentRate: "Tok prenosa",
    totalLatency: "Skupni zaostanek",
    encodeLatency: "Čas zlaganja",
    encodeLatencyMax: "Najdaljši čas zlaganja",
    transportLatency: "Čas prenašanja",
    decodeLatency: "Čas razlaganja",
    fecPercentage: "FEC odstotek",
    fecFailureTotal: "Skupno št.FEC napak",
    fecFailureInSecond: "FEC napake/sek",
    clientFPS: "Št. prejetih sličic na skundo",
    serverFPS: "Št. oddanih sličic na skundo",
    packets: "Zabojčkov",
    packetss: "Zabojčkov/sek",
    // Logging tab
    logging: "BELEŽENJE",
    //validation errors
    error_DuplicateHostname: "Naprava z tem hostname je že registrirana",
    error_InvalidIp: "Ni veljaveo oblikovan IP v4 naslov",
    //Performance graphs tab
    performanceGraphs: "GRAF ZMOGLJIVOSTI",
    performanceEncode: "Zlaganje",
    performanceDecode: "Razlaganje",
    performanceTransport: "Prenos",
    performanceOther: "Ostalo",
    performanceLatency: "Zaostanek",
    performanceFramerate: "Tok sličic",
    performanceNoDateCaptured: "Podatki niso na voljo",
});
