name: Publish to GitHub Wiki

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to wiki
        uses: cmbrose/github-docs-to-wiki@v0.24
        with:
          githubToken: ${{ secrets.GH_PAT }}
          rootDocsFolder: "wiki"
